### ISSUE TITLE
Query Counter breaks PHPUnit's @dataProvider annotation

### ISSUE THREAD

**Issue by bicpi** [liip/LiipFunctionalTestBundle#110]
Enabling the Query Counter causes an exception from Doctrine's annotation reader because the `@dataProvider` annotation is not ignored:

```
Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@dataProvider" in method Acme\DemoBundle\Controller\FooControllerTest::testBar() was never imported. Did you maybe forget to add a "use" statement for this annotation?
```

Maybe it's worth a note in the docs? Currently I'm fixing this by adding an `@IgnoreAnnotation` annotation to the test class:

```
Liip\FunctionalTestBundle\Test\WebTestCase as BaseWebTestCase;

/**
 * @IgnoreAnnotation("dataProvider")
 */
class FooControllerTest extends BaseWebTestCase
{
     /**
      * @dataProvider provideData
      */
    public function testWithData($first, $second)
    {
        // ...
    }

    public function provideData()
    {
        return array(
            array(4, 5),
            // ...
        );
    }
}
```

Please let me know what you think, I could do a PR.

Another working, but not so clean approach, somewhere before executing the tests, e.g. you own additional parent `BaseWebTestCase` class:

```
use Liip\FunctionalTestBundle\Test\WebTestCase as BaseWebTestCase;
use Doctrine\Common\Annotations\AnnotationReader;

AnnotationReader::addGlobalIgnoredName('dataProvider');

class WebTestCase extends BaseWebTestCase
{
    // ...
```

I think also applies to all other PHPUnit annoations like `@depends` etc.

**Comment by alexislefebvre** [comment]
I suggest to reopen this (or open a new Issue?), after an upgrade to LiipFunctionalTestBundle 1.4.0 I got the same problem.

Maybe there is another way to read the LiipFunctionalTestBundle annotations without having this problem with PHPUnit annotations.

**Comment by francoispluchino** [comment]
@bicpi, @alexislefebvre You can use a custom autoloader for your tests:

```php
// tests/autoload.php
<?php

use Composer\Autoload\ClassLoader;
use Doctrine\Common\Annotations\AnnotationReader;

/**
 * @var ClassLoader $loader
 */
$loader = require __DIR__.'/../app/autoload.php';

AnnotationReader::addGlobalIgnoredName('group');
AnnotationReader::addGlobalIgnoredName('dataProvider');

return $loader;
```

And add the custom autoload in phpunit config:

```xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- http://phpunit.de/manual/4.1/en/appendixes.configuration.html -->
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/4.1/phpunit.xsd"
         backupGlobals="false"
         colors="true"
         bootstrap="tests/autoload.php"
        >
    <!-- your config -->
</phpunit>

```

With this, it's not useful to putting the annotation `IgnoreAnnotation` on each class, but only one time in a unique place.

Perhaps it would be interesting to add this info to documentation of the [Caveats](https://github.com/liip/LiipFunctionalTestBundle#caveats) section?

**Comment by alexislefebvre** [comment]
@francoispluchino Thanks for the tip. The *Caveats* section already contain a note about `@IgnoreAnnotation` so it's the good place to add your explanation. Feel free to submit a PR.

**Comment by TomasVotruba** [comment]
@francoispluchino Works like a charm :hugs:  You saved me some pain, thanks!
