### ISSUE TITLE
getEntityManager is deprecated since Symfony 2.1

### ISSUE THREAD

**Issue by ghost** [liip/LiipFunctionalTestBundle#135]
"Deprecated: getEntityManager is deprecated since Symfony 2.1. Use getManager"

see:

https://github.com/liip/LiipFunctionalTestBundle/blob/master/Test/WebTestCase.php#L242

**Comment by thomas-koch-comsolit** [comment]
I don't know, which types of registries are supported and whether the following is save to do. It might also be possible to just use ```$type = $registry->getName()``` since we only expect registries of type ManagerRegistry now?

``` diff
--- a/Test/WebTestCase.php
+++ b/Test/WebTestCase.php
@@ -235,13 +235,8 @@ abstract class WebTestCase extends BaseWebTestCase
     {
         $container = $this->getContainer();
         $registry = $container->get($registryName);
-        if ($registry instanceof ManagerRegistry) {
-            $om = $registry->getManager($omName);
-            $type = $registry->getName();
-        } else {
-            $om = $registry->getEntityManager($omName);
-            $type = 'ORM';
-        }
+        $om = $registry->getManager($omName);
+        $type = $registry instanceof ManagerRegistry ? $registry->getName() : 'ORM';
```

**Comment by lsmith77** [comment]
currently we still support Symfony 2.0 .. then again .. I don't mind bumping things to 2.3
