### ISSUE TITLE
Question before PR - load yml file instead of fixture class

### ISSUE THREAD

**Issue by nicolas-bastien** [liip/LiipFunctionalTestBundle#143]
Hi,

We want to load our fixtures for testing directly with yml to be able to choose for each test which file we want to load.

Right now we extend your bundle to add this functionality directly in our project.
This functionality use Nelmoi/Alice to parse yml files

I think it can be a good idea to add it directly in LiipFunctionalTestBundle.

I can do the PR but before working on it, I want to check with you if this can be merged.

Here is an example : 

        $this->loadFixtureFiles([
            '@AppBundle/Tests/Ressources/DataFixtures/data/areaRange.yml',
            '@AppBundle/Tests/Ressources/DataFixtures/data/priceRange.yml',
        ]);

What do you think about it ?

**Comment by lsmith77** [comment]
sounds good

**Comment by nicolas-bastien** [comment]
done @lsmith77 maybe we can tag 1.1.1 before the refactoring PR ?
