### ISSUE TITLE
Problem with Version 1.2.0 on php 5.3.10

### ISSUE THREAD

**Issue by jimtonic** [liip/LiipFunctionalTestBundle#149]
The minimum php version to use this bundle is 5.3.2 according to the composer.json.
However in Tests/WebTestCase on line 373 you made used the short array syntax, that isn't available before php 5.4
So, since I updated the LiipFunctionalTestBundle from 1.1.0 to 1.2.0 I get the following error:

```
Parse error: syntax error, unexpected '[' in /opt/jenkins/ferdi/jobs/Services - BPP build/workspace/vendor/liip/functional-test-bundle/Test/WebTestCase.php on line 373
```

**Comment by lsmith77** [comment]
can you submit a PR to fix it?

**Comment by jimtonic** [comment]
sure, i have submitted a PR.

**Comment by lsmith77** [comment]
closed via https://github.com/liip/LiipFunctionalTestBundle/releases/tag/1.2.1
