### ISSUE TITLE
Load services in Fixtures

### ISSUE THREAD

**Issue by Bastien-Wink** [liip/LiipFunctionalTestBundle#158]
I can't find a way to load services (like a password encoder) in the fixtures.
My understanding of the code says we only load the $om in the fixtures not looking at services needed in services.yml.

**Comment by lsmith77** [comment]
yeah, I do not think that this is supported atm .. you can maybe explore a bit of injecting the service container is feasible.

**Comment by MTGap** [comment]
I believe this is what you're looking for @Bastien-Wink 

http://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html#using-the-container-in-the-fixtures
