### ISSUE TITLE
Class 'Liip\FunctionalTestBundle\Test\WebTestCase' not found

### ISSUE THREAD

**Issue by lusorio** [liip/LiipFunctionalTestBundle#170]
Trying to make some functional tests:

- I have in my composer.json:

     "require-dev": {
            "doctrine/doctrine-fixtures-bundle": "dev-master",
            "phpunit/phpunit": "4.8.*",
            "liip/functional-test-bundle": "dev-master"
        },

- In AppKernel.php

    if (in_array($this->getEnvironment(), array('dev', 'test'))) {
            $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();
            $bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
            $bundles[] = new Liip\FunctionalTestBundle\LiipFunctionalTestBundle();
            $bundles[] = new Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle();
        }

I've **composer update** the project and have all the bundles in my /vendor directory

**But in my tests I get a**

PHP Fatal error:  Class 'Liip\FunctionalTestBundle\Test\WebTestCase' not found in .../ClientControllerTest.php on line 11
PHP Stack trace:
PHP   1. {main}() .../ApiBundle/Tests/Controller/ClientControllerTest.php:0

Fatal error: Class 'Liip\FunctionalTestBundle\Test\WebTestCase' not found in .../ApiBundle/Tests/Controller/ClientControllerTest.php on line 11

Call Stack:
    0.0018     244624   1. {main}() .../ApiBundle/Tests/Controller/ClientControllerTest.php:0

Process finished with exit code 255

I know the class is there as I can navigate to it, even with Alt+Click in the **WebTest**

Any suggestions?

**Comment by lsmith77** [comment]
are you using the composer autoloader?

**Comment by lusorio** [comment]
Sorry, just a config issue. Thanks

**Comment by FirasGL** [comment]
what was the issue?? :p

**Comment by alexislefebvre** [comment]
@FirasGL Maybe the `use Liip\FunctionalTestBundle\Test\WebTestCase;` was missing.
