### ISSUE TITLE
My project does not use a database

### ISSUE THREAD

**Issue by Avtonom** [liip/LiipFunctionalTestBundle#179]
How do I install tests for working with Fixtures if my project does not use a database? I test my REST methods of obtaining information from external services by SOAP.

**Comment by lsmith77** [comment]
maybe look at integration with https://github.com/php-vcr/VCRBundle

**Comment by Avtonom** [comment]
Sorry, I'm Mell Fixtures!
Those. I have an array of test data to a file (3 pieces). But what would they use doctrine requires a database connection.

**Comment by lsmith77** [comment]
hmm can you provide me an example?
