### ISSUE TITLE
Alice fixture loading doesn't support custom Processors or Faker Providers

### ISSUE THREAD

**Issue by mattsnowboard** [liip/LiipFunctionalTestBundle#181]
The current fixture loader just calls directly into the static method in Alice to load fixtures. Other bundles that are for Alice only (but expose a command, not a way to load fixtures in tests like this), allow you to tag services as providers/processors and it will use them when loading with Alice.

For example: https://github.com/hautelook/AliceBundle

Could this bundle be extended to support custom Faker providers/Alice processors?

**Comment by lsmith77** [comment]
I am certainly open to merge a PR adding this.

**Comment by estahn** [comment]
@mattsnowboard @lsmith77 Any idea how to get this working. It appears the `findTaggedServiceIds` is not being called.

**Comment by lsmith77** [comment]
@estahn can you elaborate .. which ``findTaggedServiceIds`` isn't being called?

**Comment by estahn** [comment]
@lsmith77 Sorry, that was a bit unclear. I tried to get this working in order to provide a pull request. Basically you're supposed to define a "custom provider" or "custom processor" as a service and tag it, e.g.

```php
# app/config/services.yml

services:
    faker.provider.foo:
        class: AppBundle\DataFixtures\Faker\Provider\FooProvider
        tags: [ { name: hautelook_alice.faker.provider } ]
```

That should somehow be picked up by the `ContainerBuilder::findTaggedServiceIds` i guess, which doesn't seem the case.

**Comment by estahn** [comment]
If i change the following line it's working, but it will obviously introduce a dependency to hautelook alice bundle.

https://github.com/liip/LiipFunctionalTestBundle/blob/0b65790fc70095dacb9c54164996ea0559ef40a8/Test/WebTestCase.php#L542

Change to:
```php
        // Check if the Hautelook AliceBundle is registered and if yes, use it instead of Nelmio Alice
        $hautelookLoaderServiceName = 'hautelook_alice.fixtures.loader';
        $result = $this->getContainer()->has($hautelookLoaderServiceName) ?
            $this->getContainer()->get($hautelookLoaderServiceName)->load(new Doctrine($om), $files) :
            Fixtures::load($files, $om);

        return $result;
```

**Comment by alexislefebvre** [comment]
@estahn *but it will obviously introduce a dependency to hautelook alice bundle* It looks like your code will use the Doctrine fixtures loader if AliceBundle is not loaded, so there is no dependency?

The Bundle already have code specific to [PHPCR](https://github.com/liip/LiipFunctionalTestBundle/blob/0b65790fc70095dacb9c54164996ea0559ef40a8/Test/WebTestCase.php#L363), I think it's not a problem to add code specific to another bundle.

**Comment by lsmith77** [comment]
I am fine adding an optional dependency here ..

**Comment by estahn** [comment]
See #244
