### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by luispabon** [liip/LiipFunctionalTestBundle#183]
Please, cut up a new release. There are some fixes lying about since may such as https://github.com/liip/LiipFunctionalTestBundle/commit/a6d77ab67e78fd757d33eace6697b8596e2f115d that would be great to have available without pulling dev-master.

**Comment by nilov** [comment]
Join, I have the same problem! Can't update to master because it conflicts with sonata admin bundle. Really need this commit https://github.com/liip/LiipFunctionalTestBundle/commit/a6d77ab67e78fd757d33eace6697b8596e2f115d

**Comment by lsmith77** [comment]
https://github.com/liip/LiipFunctionalTestBundle/releases/tag/1.3.0

**Comment by nilov** [comment]
Thank you! But unfortunately because of this class DataCollectingValidator a bundle now is not compatible with a stable version of sonata admin bundle.
