### ISSUE TITLE
The service definition "validator" does not exist.

### ISSUE THREAD

**Issue by andriylekh** [liip/LiipFunctionalTestBundle#185]
After 58bb1d2c6717d08ddd2cc3b90ba3567c55942aa9 commit have a problem with loading validator.

**Comment by lsmith77** [comment]
I doubt that this could be caused by that commit. I suspect its more related to potentially having updated other dependencies.

**Comment by sc0rp10** [comment]
@lsmith77 how do I test bundle without internal unit-tests? Maybe you're have any ideas? I can fix it issue, but i don't know how can I check my work.

**Comment by lsmith77** [comment]
yeah. essentially tests need to be created from scratch :-/

**Comment by sc0rp10** [comment]
@andriylekh any details? symfony version, stacktrace etc

**Comment by lsmith77** [comment]
I created https://github.com/liip/LiipFunctionalTestBundle/pull/189/files

**Comment by tarioch** [comment]
I'm getting exactly the same issue:
https://travis-ci.org/tarioch/eveapi-fetcher-bundle

**Comment by lsmith77** [comment]
should be fixed now
