### ISSUE TITLE
Compatibility with Symfony 3.0

### ISSUE THREAD

**Issue by MassiveHiggsField** [liip/LiipFunctionalTestBundle#186]
I cannot update to Symfony 3.0 because this bundle requires symfony/validator ~2.5, but symfony/symfony 3.0 needs symfony/validator 3.0. Output from composer 

    Problem 1
    - liip/functional-test-bundle 1.3.1 requires symfony/validator ~2.5 -> satisfiable by symfony/symfony[v2.8.0], symfony/validator[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.8.0].
    - liip/functional-test-bundle 1.3.0 requires symfony/validator ~2.5 -> satisfiable by symfony/symfony[v2.8.0], symfony/validator[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.8.0].
    - liip/functional-test-bundle 1.3.1 requires symfony/validator ~2.5 -> satisfiable by symfony/symfony[v2.8.0], symfony/validator[v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.8.0].
    - Can only install one of: symfony/symfony[v3.0.0, v2.8.0].
    - don't install symfony/validator v2.5.0|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.5.1|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.5.10|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.5.11|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.5.12|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.5.2|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.5.3|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.5.4|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.5.5|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.5.6|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.5.7|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.5.8|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.5.9|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.6.0|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.6.1|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.6.10|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.6.11|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.6.12|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.6.2|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.6.3|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.6.4|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.6.5|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.6.6|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.6.7|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.6.8|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.6.9|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.7.0|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.7.1|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.7.2|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.7.3|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.7.4|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.7.5|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.7.6|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.7.7|don't install symfony/symfony v3.0.0
    - don't install symfony/validator v2.8.0|don't install symfony/symfony v3.0.0
    - Installation request for symfony/symfony ~3.0-stable -> satisfiable by symfony/symfony[v3.0.0].
    - Installation request for liip/functional-test-bundle ~1.3-stable -> satisfiable by liip/functional-test-bundle[1.3.0, 1.3.1].

**Comment by sc0rp10** [comment]
see https://github.com/liip/LiipFunctionalTestBundle/pull/187

**Comment by MassiveHiggsField** [comment]
Great thanks.

**Comment by lsmith77** [comment]
merged that PR .. however I think we will still need to update the bundle to actually handle some deprecated interfaces
