### ISSUE TITLE
Backwards incompatible change in 1.3.0 authentication parameter of WebTestCase::makeClient

### ISSUE THREAD

**Issue by ivoazm** [liip/LiipFunctionalTestBundle#192]
There was undocumented backwards incompatible change in 1.3.0 version.

v1.2.2
```php
$client = static::makeClient(
    [
        'username' => 'user@example.com',
        'password'   => 'test123',
    ]
);
```

v1.3.0
```php
$client = static::makeClient(
    [
        'PHP_AUTH_USER' => 'user@example.com',
        'PHP_AUTH_PW'   => 'test123',
    ]
);
```

**Comment by lsmith77** [comment]
hmm can you have a look .. I think it should be possible to fix this BC break in a new release.

**Comment by Arthurhall** [comment]
i will look at it

**Comment by lsmith77** [comment]
https://github.com/liip/LiipFunctionalTestBundle/pull/193

**Comment by lsmith77** [comment]
https://github.com/liip/LiipFunctionalTestBundle/releases/tag/1.3.3

**Comment by ivoazm** [comment]
Thank you @lsmith77  @Arthurhall
