### ISSUE TITLE
Keep PHP 5.3 compatibility in Test/WebTestCase.php

### ISSUE THREAD

**Issue by alexislefebvre** [liip/LiipFunctionalTestBundle#194]
The changes from #193 use short array syntax from PHP 5.4, This code fails with PHP 5.3: https://travis-ci.org/alexislefebvre/LiipFunctionalTestBundle/jobs/97735960#L285

It uses the short array syntax which appeared with PHP 5.4: http://php.net/manual/en/migration54.new-features.php

Since LiipFunctionalTestBundle is compatible with Symfony 2.3 which is compatible with PHP 5.3, the *old* array syntax should be used.

This is similar to this previous issue: #149.

**Comment by lsmith77** [comment]
https://github.com/liip/LiipFunctionalTestBundle/commit/0981fc0a18678b50a53410496239b602dc5a355b
