### ISSUE TITLE
liip_functional_test.query.max_query_count value is ignored

### ISSUE THREAD

**Issue by alexislefebvre** [liip/LiipFunctionalTestBundle#207]
If I set the value of the `liip_functional_test.query.max_query_count` parameter to `0` in [`Tests/App/config.yml`](https://github.com/liip/LiipFunctionalTestBundle/blob/ad234a8450fce3e10d37186de689b4aa6fe32898/Tests/App/config.yml#L32), the tests should report an error because there is one DB query in the `Tests\Test\WebTestCaseTest::testUserWithFixtures` test, but there is no error.

But if I edit the `Resources/config/functional_test.xml` file by changing the value of [`liip_functional_test.query.max_query_count`](https://github.com/liip/LiipFunctionalTestBundle/blob/ad234a8450fce3e10d37186de689b4aa6fe32898/Resources/config/functional_test.xml#L20), it works and the tests fail:

> $ vendor/bin/phpunit
> PHPUnit 5.1.3 by Sebastian Bergmann and contributors.
> 
> ....E...                                                            8 / 8 (100%)
> 
> Time: 418 ms, Memory: 35.50Mb
> 
> There was 1 error:
> 
> 1) Liip\FunctionalTestBundle\Tests\Test\WebTestCaseTest::testUserWithFixtures
> Liip\FunctionalTestBundle\Exception\AllowedQueriesExceededException: Allowed amount of queries (0) exceeded (actual: 1).

Current code:

    <parameter key="liip_functional_test.query.max_query_count">null</parameter>

Updated code which trigger the exception:

    <parameter key="liip_functional_test.query.max_query_count">0</parameter>

So it seems that the `liip_functional_test.query.max_query_count` value defined in the `config.yml` is not read. I have the same result while testing another bundle which use LiipFunctionalTestBundle.

**Comment by lsmith77** [comment]
hmm I currently do not use this feature .. so maybe it was broken :(

**Comment by lsmith77** [comment]
if you have time to look into this issue .. then I think we are ready to release 1.4.0
https://github.com/liip/LiipFunctionalTestBundle/compare/1.3.4...master

**Comment by alexislefebvre** [comment]
This feature seems to be broken, I think the root of the problem is the configuration which is not correctly readen, these values are ignored: https://github.com/liip/LiipFunctionalTestBundle/blob/eb37957b8a63b2cb0a46f5256d5ddc1d33e1094c/Tests/App/config.yml#L31

I think this part should be more or less rewritten, for example by defining default values in the Configuration builder and not in [`Resources/config/functional_test.xml`](https://github.com/liip/LiipFunctionalTestBundle/blob/master/Resources/config/functional_test.xml), see [ Defining and Processing Configuration Values](http://symfony.com/doc/current/components/config/definition.html#adding-node-definitions-to-the-tree) for reference.

---

About the changes between 1.3..4 and master, I just checked and most of the code is used only during tests and should not change the behaviour of the Bundle.

The updated files which are used when using this Bundle are:
 - `DependencyInjection/Configuration.php`
 - `Resources/config/functional_test.xml`
 - `Test/Html5WebTestCase.php`
 - `Test/WebTestCase.php`

They should not break the bundle, but it's hard to assure you…

**Comment by alexislefebvre** [comment]
I think that the problem come from the [service](https://github.com/liip/LiipFunctionalTestBundle/blob/790c82c7a2a4946659dcd724be35208e2407b9ad/Resources/config/functional_test.xml#L42) which call the `%liip_functional_test.query.max_query_count%` parameter, maybe it loads the value defined sooner in the `Resources/config/functional_test.xml` file instead of reading the value defined in the `config.yml` file.

**Comment by alexislefebvre** [comment]
> This feature seems to be broken, I think the root of the problem is the configuration which is not correctly readen, these values are ignored

This is not as bad as I thought, the `liip_functional_test.query.count_client`value is not loaded but there is no problem with the other parameters.

**Comment by alexislefebvre** [comment]
In #233, the added test check the value of `liip_functional_test.query.max_query_count` and it is correctly defined. So the problem probably comes from the injection of the value in the service.

**Comment by lsmith77** [comment]
FYI .. I created a 1.4 milestone and added some tickets to there .. though I think none of them are real show stoppers ..

**Comment by alexislefebvre** [comment]
I may have found the answer:

> Symfony2 doesn't support reading individual elements on a parameter array using the `%` notation.

Source: http://stackoverflow.com/questions/19919679/symfony2-how-to-read-parameters-array-in-config-yml/19920871#19920871

The service use `liip_functional_test.query.max_query_count` but `liip_functional_test.query` is an array, its value can't be used directly.

**Comment by alexislefebvre** [comment]
I created two PR on my repository to address this problem:

 - https://github.com/alexislefebvre/LiipFunctionalTestBundle/pull/6 defines the service through PHP and access to `liip_functional_test.query` as an array with a `max_query_count` key. A test check that the limit of queries throws an exception
 - https://github.com/alexislefebvre/LiipFunctionalTestBundle/pull/7 uses a `max_query_count` parameter instead of `query.max_query_count`. It works with some small changes compared to the previous PR.

**Comment by alexislefebvre** [comment]
Here is a simpler PR with ideas from both PRs: https://github.com/alexislefebvre/LiipFunctionalTestBundle/pull/8

I opened it by error on this repository instead of my fork, I can re-open it if needed: https://github.com/liip/LiipFunctionalTestBundle/pull/236

**Comment by alexislefebvre** [comment]
@colinfrei I see that this feature has been introduced in #70, can you please take a look at this issue and the #236 PR as a solution? Thanks.

**Comment by lsmith77** [comment]
we can close this one then?

I guess we should make a new release (1.4.0) then as well?

**Comment by alexislefebvre** [comment]
@lsmith77 Thanks for the merge. I think you can make a new release now. :+1:
