### ISSUE TITLE
Tests on Symfony 2.3 use Symfony 2.3.1

### ISSUE THREAD

**Issue by alexislefebvre** [liip/LiipFunctionalTestBundle#208]
The tests using Symfony 2.3 declare this variable: `COMPOSER_FLAGS="--prefer-lowest"`

Here is the result:

> $ export COMPOSER_FLAGS="--prefer-lowest"
> $ composer update $COMPOSER_FLAGS --prefer-dist
>
> You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> […]
>   \- Installing symfony/symfony (v2.3.1)
>     Loading from cache

Source: https://travis-ci.org/liip/LiipFunctionalTestBundle/jobs/101389945#L143

I guess the goal is to avoid BC breaks by testing against the oldest version but I'm pretty sure nobody use this version published in 2013. Should it use the last version of Symfony 2.3 instead?

Related commit: 3e4e8921b86eebf9a016d941c8ec824282564ca7

**Comment by lsmith77** [comment]
we want to support 2.3 .. but feel free to increase the lowest allow version of Symfony 2.3 .. but try to pick the lowest that works.

**Comment by alexislefebvre** [comment]
Ok, I like this idea. I will change the version in the #209 PR.

**Comment by alexislefebvre** [comment]
I didn't had to change the dependencies, the error was due to an error in my code, not to the `--prefer-lowest` flag. Sorry for the inconvenience.
