### ISSUE TITLE
 annotation "@dataProvider"  issues

### ISSUE THREAD

**Issue by kYem** [liip/LiipFunctionalTestBundle#214]
I'm constantly getting issues with `@dataProvider` annotation failing on the first run, before cache is generated. That means first test that have `dataProvider` will always fail.

In the documentation it mentions enabling `Query Counter` will break dataProvider (major issue IMO), the problem I have is that i did not enabled it myself, but it is enabled by default. My configuration:

``` yml
liip_functional_test:
    cache_sqlite_db: true
```

`* @IgnoreAnnotation("dataProvider")` did not help, but https://github.com/liip/LiipFunctionalTestBundle/issues/110 mentioned other way to solve the  issue by adding

 `AnnotationReader::addGlobalIgnoredName('dataProvider');` 

in your own BaseWebTestCase class. In my case this solves the issue when cache is cleared and new tests picks up the global ignore, but as @bicpi mentioned that is not really a clean solution either.

Ideally I would like to disable the `Query Count` that is causing the issue in the first place. But I could not find a way to do that yet. 

Second thing would be to update documentation with `AnnotationReader::addGlobalIgnoredName('dataProvider');`  solution as well.

The long term solution should be to ignore all phpunit annotations by default.

**Comment by alexislefebvre** [comment]
*but it is enabled by default* How do you see that? It should be disabled by default. I tried to use it during tests by it's always disabled for me, whatever the configuration is.

**Comment by kYem** [comment]
I am assuming it is, as you can see my configuration only have `cache_sqlite_db: true` and nothing else and since I'm getting the `[Semantical Error] The annotation "@dataProvider" in method ...::testListAction() was never imported. Did you maybe forget to add a "use" statement for this annotation?` it is confirming that it is in fact enabled?

I'm using 
`liip/functional-test-bundle                     1.3.4`
`symfony/symfony                                 v2.8.1`
`phpunit/phpunit                                 4.8.21`

**Comment by alexislefebvre** [comment]
I [added `@dataProvider` in tests](https://github.com/alexislefebvre/LiipFunctionalTestBundle/commit/f381169ee6fd9e1460982464c8d38ca805afced0#diff-ab2cc27d1cdfd485cf44b42243abdc9aR331) and it [worked on Travis CI](https://travis-ci.org/alexislefebvre/LiipFunctionalTestBundle/builds/102111725). Then I copy and pasted this code in another project which use this bundle and it worked too. How can your problem be reproduced?

**Comment by kYem** [comment]
I finally managed to track down the issue, so the problem was caused by one of my test class that have the correct file name  like `SampleControllerTest.php` but the class name was `SampleController`

So if run the directory that included that unit test class, the first test would fail with `@dataProvider` not imported error message due to missing `Test` in the class name.

It was really hard to find this problem, as the tests would fail in the different class and would only happen if the cache was empty.

Luckly I noticed that one part of the test suite would pass when I specified the test class directly, but as I would broaden the target to the src directory it would fail.

**Comment by kYem** [comment]
So I dig a bit deeper and  found out the issue was happening during cache warm up by `JMS\DiExtraBundle\HttpKernel\ControllerInjectorsWarmer` registering `SampleControllerTest.php` file as controller and loading meta data.

**Comment by lsmith77** [comment]
is there anything you think we can add to the docs?

**Comment by kYem** [comment]
The problem in this case was really DiExtraBundle and class name, but because of the caveats part of the readme I assumed it would be Liip bundle.

The `AnnotationReader::addGlobalIgnoredName('dataProvider');` suggestion could be there as well.

I think a note of possible issue with class name and DiExtraBundle which as I believe it is quite common to use it, could help others that might run into similar issue.

It could be along the lines of:

* If you did not enabled `QueryCount` annotation, but are still getting `@dataProvider` annotation not imported error, please make sure all your controller tests have class name ending with `Test`

**Comment by tackerm** [comment]
This 

`please make sure all your controller tests have class name ending with Test`

is a phpunit requirement anyways: https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html

**Comment by alexislefebvre** [comment]
A test using `@dataProvider` has been added and data is loaded without any error: https://github.com/liip/LiipFunctionalTestBundle/blob/72c8feff5fe6765e33b58397d5cbc98923d3b4b9/Tests/DependencyInjection/ConfigurationTest.php#L30

**Comment by alexislefebvre** [comment]
@kYem there was a problem with annotations, it has been fixed in d1a2ca1c661f83022868e78603b948dc8c0153ad, can you please try to use the same fix? Thanks.

**Comment by kYem** [comment]
Closing this as it was really a naming issue, the commit you are referencing does not change anything in my case, as I already had the setup for my phpunit

**Comment by alexislefebvre** [comment]
@kYem oops, I'm sorry, I thought it was related.
