### ISSUE TITLE
Method `WebTestCase::getKernelClass()` seems to be not used in any part of the bundle

### ISSUE THREAD

**Issue by Aerendir** [liip/LiipFunctionalTestBundle#217]
It seems the method isn't used anyway.

Am I wrong?

I've inspected the method with PHPStorm to find usages of the method and also with simple searches through the code it seems it isn't used.

As it also raise Sensio Insights violations, maybe it is appropriate to remove it?

**Comment by lsmith77** [comment]
This class is in ``Symfony\Bundle\FrameworkBundle\Test\KernelTestCase`` which is a "grant" parent of this class.

**Comment by Aerendir** [comment]
Yes, I've just seen it.
But, if it is in the parent class, why is replicated in WebTestCase too? Maybe am I missing something?
May it be removed?

**Comment by lsmith77** [comment]
its used in ``KernelTestCase::createKernel()``

**Comment by Aerendir** [comment]
Yes, and that class has the method too, so the one in `WebTestCase()` is a replica of it. It seems to me it is superfluous, isn't it?

**Comment by lsmith77** [comment]
its not a replica .. it extends it and fallback to the old one for specific situations:

```
    protected static function getKernelClass()
    {
        $dir = isset($_SERVER['KERNEL_DIR']) ? $_SERVER['KERNEL_DIR'] : self::getPhpUnitXmlDir();

        list($appname) = explode('\\', get_called_class());

        $class = $appname.'Kernel';
        $file = $dir.'/'.strtolower($appname).'/'.$class.'.php';
        if (!file_exists($file)) {
            return parent::getKernelClass();
        }
        require_once $file;

        return $class;
    }
```

The intention of this is to enable more flexibility in the structuring of the app dir .. specifically to support multiple kernels.

**Comment by Aerendir** [comment]
Ok, as not told :)
