### ISSUE TITLE
runCommand(): use CommandTester (Enhancement)

### ISSUE THREAD

**Issue by Aerendir** [liip/LiipFunctionalTestBundle#219]
I'm trying to use the `WebTestCase::runCommand()` method.

I have yet implemented my unit test to test command, but, as I've anyway extend `WebTestBundle` to load fixtures, I like to also use other useful methods that the bundle provides.
So II'd like to rewrite my tests to use those methods.

Now I'm working on a command and seen the code of the method `WebTestCase::runCommand()`.

I noted it doesn't use the helpful `Symfony\Component\Console\Tester\CommandTester()` class: is there a reason for this? Or may be the `CommandTester` class were released after the `WebTestCase::runCommand()`?

Can someone help me understand?

**Comment by lsmith77** [comment]
yes ``WebTestCase::runCommand()`` was created years before ``Symfony\Component\Console\Tester\CommandTester()``

**Comment by Aerendir** [comment]
I'll work on it ASAP...

**Comment by giosh94mhz** [comment]
This would be a cool addition, since with the current `runCommand` there is no status code returned.

Here's what I did:

```php
    $tester = new CommandTester($this->command);
    $this->assertEquals($this->command->getName(), 'my:name');
    $this->assertEquals(0, $tester->execute());
    $output = $tester->getOutput();
```

**Comment by magnetik** [comment]
I've gave it a go in the PR above.

**Comment by martiis** [comment]
I recently updated and got some issues. CommandTester does not dispatch console events and some tests started failing. Is there a solution?

**Comment by Jean85** [comment]
Are you sure that you're not referencing a different kernel?
