### ISSUE TITLE
Permit to create more than one user in configuration and choose with which one to login

### ISSUE THREAD

**Issue by Aerendir** [liip/LiipFunctionalTestBundle#221]
Currently, using the configuration file it is possible to configure only one user to create a logged in client.

It would be very useful if the bundle allows to configure more than one user in the configuration file and choose with which one to connect from the test itself.

I think this may cause a BC as currently the way of configuring the user in the `.yml` file is this:

    liip_functional_test:
        authentication:
            username: "a valid username"
            password: "the password of that user"

The solution I imagine is something like this:

    liip_functional_test:
        authentication:
            user1:
                username: "a valid username"
                password: "the password of that user"
            user2:
                username: "a valid username"
                password: "the password of that user"
            ...

I can implement this, but, as I'm not so practical with the `TreeBuilder`, I don't know if it is possible to maintain a backward compatibility.

To maintain the backward compatibility, someone should check if the `authentication` node is an array that contains an array (multiple users) or contains only scalar nodes (only one user set).

**Comment by alexislefebvre** [comment]
How will you use this feature? Will you have different properties linked to these users? All these users will have the same rights (in fact, none), this won't help you during tests.

**Comment by Aerendir** [comment]
This will help me during tests as the same page shows different things to different users.

In fact, if the user is the owner of the entity, the page shows him some admin menu links; if the user is not the owner, but is someone who had interacted with the entity, the page shows some other info to him.

Obviously there are some "default" info shown on the page and, on the base of the current user, only small things change. But I have to check this.

Anyway, I've just solved the problem of the backward compatibility, and I'm going to work on the `makeClient` method to make it able to handle a default connection if the developer uses the current way of handling default users. Give me time and I will send a PR with the complete solution and updated documentation! :)

**Comment by alexislefebvre** [comment]
I think I understand what you're trying to do, what I don't understand is *how*.

Can you please explain how you link the users created in your examples with the entities? In other words, how do you declare that *the user is the owner of the entity*? Do you use the email address? Do you create data fixtures? In fact, I don't know how the actual code works, I never checked if it persist users in the database or if it only create users on the fly. If this is the case, even the actual code is useless because an user without any right is useless if our code use rights.

I personally use data fixtures in my tests, it gives full control on rights, links to other entities, etc.

**Comment by Aerendir** [comment]
I use the ACL to handle rights and permissions. I use fixtures too and in them I set the ACLs and persist them to a SQlite database.

Then I check for the permissions in the Twig template to decide if the user can see the links or not (and the controllers do obviously a back-end check to avoid hacks).

**Comment by Aerendir** [comment]
@alexislefebvre I've just understand what you've tried to tell me.
In my situation I should use `loginAs($fixtures->getReference('user'))`.

Writing the tests for this new feature I saw how to correctly use the method and realize it is not so useful to put credentials in `config_test.yml`.

Anyway I wrote the feature, it is compatible with the old notation and is yet pushed...

And, anyway, I will update the documentation so that it will be clearer... This caused me a lot of lost time...

**Comment by Aerendir** [comment]
This is not yet relevant. I updated the documentation "fixing" issue #88 in PR #225.

**Comment by alexislefebvre** [comment]
Maybe it would be easier to create tests users by using Symfony security providers: http://symfony.com/doc/2.8/book/security.html#b-configuring-how-users-are-loaded

**Comment by Aerendir** [comment]
Maybe, anyway I'm now able to use `WebTestCase::loginAs()` that is much simpler as I yet have all fixtures wrote...
