### ISSUE TITLE
Add `tearDown()` method to `WebTestCaseTest` (Enhancement)

### ISSUE THREAD

**Issue by Aerendir** [liip/LiipFunctionalTestBundle#224]
Set `$this->client` to `null`.

**Comment by alexislefebvre** [comment]
Mhh, you changed the test which test the Bundle itself, not the actual code used when the Bundle is used as a dependency, see the [`Test`](https://github.com/liip/LiipFunctionalTestBundle/tree/master/Testà directory.

**Comment by Aerendir** [comment]
Yes, I changed the test...

**Comment by alexislefebvre** [comment]
I'm sorry, I thought it was an error. I tried your code and it didn't changed the memory usage reported by PHPUnit. Do you see a difference?

**Comment by Aerendir** [comment]
@alexislefebvre , yes, it didn't changed the memory usage... Maybe... But this is a best practice, and while currently it didn't impact much more, in the future it'll may.

Is something related to the approach: if we "dirty" the tests, we have to clean. Viceversa, in the long run we will see a lot of garbage not collected.

The besta example is `WebTestCase` that consumes a lot of memory while, using the `tearDown()` method, we could free up it and speed up the tests.
