### ISSUE TITLE
`WebTestCase::retrieveVerbosityLevel()` always returns StreamOutput::VERBOSITY_NORMAL (Bug)

### ISSUE THREAD

**Issue by Aerendir** [liip/LiipFunctionalTestBundle#229]
I'm trying to use `WebTestCase::runCommand()` but it ever returns an empty output while I'm expecting something.

In fact, to get the output I need, I have to set the `verbosity_level` to `debug`.

But the method always returns `StreamOutput::VERBOSITY_NORMAL`.

Going deeper in the issue, I found the bug is in the method `WebTestCase::getVerbosityLevel()` that works this way:

```php
private function retrieveVerbosityLevel()
    {
        // Returns the local verbosity level
        if ($this->verbosityLevel) {
            $verbosity = 'StreamOutput::VERBOSITY_'.strtoupper($this->verbosityLevel);
            if (defined($verbosity)) {
                return $verbosity;
            }
        }

        // Returns the global verbosity level
        if ($this->getContainer()->hasParameter('liip_functional_test.command_verbosity')) {
            $verbosity = 'StreamOutput::VERBOSITY_'.strtoupper($this->getContainer()->getParameter('liip_functional_test.command_verbosity'));
            if (defined($verbosity)) {
                return $verbosity;
            }
        }

        // Returns the default verbosity level
        return StreamOutput::VERBOSITY_NORMAL;
    }
```

The problem is in the checks `if (defined($verbosity))` that seems ever return `false`.

In fact, trying to print some breakthrough, the method ever fallbacks to the default `verbosity_level` while I'm configuring it as `debug` (I've tried to configure it both as local with `$this->verbosityLevel = 'debug'` and as global, by setting in the `config_test.yml` the key `liip_functional_test.command_verbosity`).

This is the modified method I've used to discover the problem:

```php
private function retrieveVerbosityLevel()
    {
        // Returns the local verbosity level
        if ($this->verbosityLevel) {
            printf("Local verbosity is set to %s", $this->verbosityLevel);
            $verbosity = 'StreamOutput::VERBOSITY_'.strtoupper($this->verbosityLevel);
            if (defined($verbosity)) {
                return $verbosity;
            } else {
                printf(" but the constant doesn't exist.\n", $this->verbosityLevel);
            }
        }

        // Returns the global verbosity level
        if ($this->getContainer()->hasParameter('liip_functional_test.command_verbosity')) {
            printf("\nGlobal verbosity is set to %s", $this->getContainer()->getParameter('liip_functional_test.command_verbosity'));
            $verbosity = 'StreamOutput::VERBOSITY_'.strtoupper($this->getContainer()->getParameter('liip_functional_test.command_verbosity'));
            if (defined($verbosity)) {
                return $verbosity;
            }
        } else {
            printf(" but the constant doesn't exist.\n", $this->verbosityLevel);
        }

        printf("\nFallback to the default value of verbosity");
        // Returns the default verbosity level
        return StreamOutput::VERBOSITY_NORMAL;
    }
```

Can someone confirm the bug, please?

**Comment by alexislefebvre** [comment]
It seems that the configuration loading is broken (see #207 for an example). I was able to change parameters by changing values in the `Resources/config/functional_test.xml` file, the parameters defined in `config*.yml` were never loaded.

**Comment by alexislefebvre** [comment]
> I'm trying to use `WebTestCase::runCommand()` but it ever returns an empty output while I'm expecting something.

That's strange, the following test works, the output is successfully tested: https://github.com/liip/LiipFunctionalTestBundle/blob/master/Tests/Command/CommandTest.php

**Comment by Aerendir** [comment]
Yes, it's strange...
In the mean time I looked for a solution, and found this thread on Stackoverflow. [This answer](http://stackoverflow.com/a/7506608/1399706) is interesting.

I'll go deeper...

**Comment by Aerendir** [comment]
@alexislefebvre , I've just done the test and it works because the output is wrote through `$output->writeln()`.

In fact it should fail.

Try to change the method `retrieveVerbosityLevel()` with the one I provided with the `printf`.
This is the result:

```console
MacBook-Pro-di-Adamo:LiipFunctionalTestBundle Aerendir$ phpunit --filter=CommandTest
PHPUnit 5.1.4 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)
Global verbosity is set to normal
Fallback to the default value of verbosityLocal verbosity is set to debug but the constant doesn't exist.

Global verbosity is set to normal
Fallback to the default value of verbosityLocal verbosity is set to debug but the constant doesn't exist.

Global verbosity is set to normal
Fallback to the default value of verbosity

Time: 3.31 seconds, Memory: 29.75Mb

OK (1 test, 6 assertions)
```

In my command implementation, the output is done through the logger (Monolog) and so it fails.

That test should return `false`.

**Comment by Aerendir** [comment]
This may be closed I think...
