### ISSUE TITLE
plainPassword not encoded to password field when using Alice

### ISSUE THREAD

**Issue by PorridgeBear** [liip/LiipFunctionalTestBundle#248]
I am trying to use my Alice fixtures within the context of a functional test. An example Alice fixture in users.yml is

```
customer_1:
        email (unique): foo@acme.com
        plainPassword: sesamestreet
        firstName: Customer
        lastName: One
```

When running CLI hautelook_alice:doctrine:fixtures:load the fixture works - user->plainPassword is encoded with bcrypt into the user->password field and the record is inserted into the database.

Within the context of a Liip WebTestCase however I get a password field violation:

```
Doctrine\DBAL\Driver\PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: user.password
```

This is because the SQL being generated is setting password as NULL - the process of encoding plainPassword is not working. This is the case whether I use MySQL Doctrine or SQLite Doctrine.

In the test I use the loadFixtureFiles helper as suggested by Liip to load Alice based fixtures:

```
public function setUp()
    {
        $this->loadFixtureFiles(array(
            '@AcmeBundle/DataFixtures/ORM/users.yml'));
```

I can see from the SQL that the fixture and Alice and Faker are mostly working as there is random data being generated by the Faker formatters/providers in my users.yml:

```
'INSERT INTO user (email, password, first_name, last_name, roles, status, confirmation_token, created_at, updated_at, mobile, address_line1, address_code, image_name, image_link, deleted_at, reason_for_deletion, crm_id, type) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["foo@acme.com", null, "Customer", "One", "a:1:{i:0;s:13:\"ROLE_CUSTOMER\";}", "enabled", null, "2016-02-22 21:56:12", "2016-02-22 21:56:12", 62616808050, "932 Stroman River", "85556-2307", null, null, null, null, null, "customer"]:
```

It's just that password is being set NULL.

I've tried a range of things none of which work. Suggestions welcome.

Cheers

**Comment by alexislefebvre** [comment]
Do you need a special value for this field? Here is a workaround: use [`<name()>`](https://github.com/liip/LiipFunctionalTestBundle/blob/6845255a4826143846e7c83504d219a376c9fe91/Tests/App/DataFixtures/ORM/user.yml).

**Comment by PorridgeBear** [comment]
Yes, since my integration tests then test login against email/password - the database value needs to be a bcrypted password. I also tried a similar workaround but where I copy an already generated set of bcrypted password values but this causes undesirable effects.

```
Couldn't generate random unique value in 128 tries.
```

**Comment by PorridgeBear** [comment]
If I could just load my ORM/AppFixtures.php which in turn loads Alice yml files AND includes a custom bcrypt provisioner function then this would work but Liip only seems to load Alice from yml files and so bypasses AppFixtures.php

**Comment by alexislefebvre** [comment]
Can you please provide a reproducible example? When and how is `plainPassword` is crypted to the password? Is it done by a Bundle? Thanks.

**Comment by PorridgeBear** [comment]
When I manually work with my User entity, I convert the plainPassword into password myself with something like this in create and update controller actions:

```
$this->get('security.password_encoder')->encodePassword($user, $user->getPlainPassword())
```

However, there must be some magic happening with the CLI fixtures

```
app/console hautelook_alice:doctrine:fixtures:load
```

Since that does not interact with my controllers or my code but still manages to encode the fixture password

```
plainPassword: somepassword
```
Into the User.password field per the configured (security.yml) encoder for the User entity.

My assumption is that the CLI fixtures command is working with the security configuration since in there I have a firewall configured with the name of the plain password entry field. 

```
password_parameter: _plainPassword
```

This is then likely encoded by the security system by virtue of the security config: 

```
encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AcmeBundle\Entity\User: bcrypt
````

So however Liip is working with fixtures is not invoking whatever the doctrine or Alice fixture commands do is my analysis.

**Comment by alexislefebvre** [comment]
@PorridgeBear can you please try with the 1.5 version? It includes a new loader which use HautelookAliceBundle, see #146.

**Comment by PorridgeBear** [comment]
You're right, the latest version does indeed work as expected. Closing this issue.

**Comment by pfleu** [comment]
Do you know if the "magic" hashing of the password still works with symfony 4 / hautelook 2.3 ? I'm getting  the "Integrity constraint violation: 19 NOT NULL constraint failed: user.passwor"
