### ISSUE TITLE
Conflict with SonataAdminBundle::setValidator

### ISSUE THREAD

**Issue by billsworld** [liip/LiipFunctionalTestBundle#249]
After installing the SonataAdminBundle and running my test suite I am getting the following errors

```Argument 1 passed to Sonata\AdminBundle\Admin\Admin::setValidator() must implement interface Symfony\Component\Validator\ValidatorInterface, Liip\FunctionalTestBundle\Validator\DataCollectingValidator given```

I have not been able to dig into this yet, but it seems very strange. Any thoughts?

**Comment by alexislefebvre** [comment]
Are your dependencies up-to-date? See #178.

What bundles do you use? Some bundles can trigger this error, see #212.

**Comment by billsworld** [comment]
Updating SonataAdmin to the dev-master version fixes the issue. Hopefully this gets resolved in the upcoming 2.4 release.
