### ISSUE TITLE
Autoload related fixtures

### ISSUE THREAD

**Issue by ghost** [liip/LiipFunctionalTestBundle#252]
Would be great to be able automatically load fixture files for which references are exists in the current fixture file. This feature is available now?

**Comment by alexislefebvre** [comment]
Did you try [https://github.com/doctrine/data-fixtures#dependentfixtureinterface](https://github.com/doctrine/data-fixtures#dependentfixtureinterface)?

**Comment by alexislefebvre** [comment]
Can you please explain your problem? With Doctrine's `OrderedFixtureInterface` or `DependentFixtureInterface` you can make references between fixtures. And thanks to [database caching](https://github.com/liip/LiipFunctionalTestBundle#tips-for-fixture-loading-tests), tests can be fast.

**Comment by lsmith77** [comment]
ping @Yakimun

**Comment by alexislefebvre** [comment]
Hi @yakimun, do you still have a problem with this bundle?
