### ISSUE TITLE
Prepare 1.6.0 release

### ISSUE THREAD

**Issue by alexislefebvre** [liip/LiipFunctionalTestBundle#254]
Follow up of #253.

- [x] Add a link to paratest.md in README.md
- [x] composer.json: in `"suggest"`, replace `"brianium/paratest"` with an explanation
- [x] fix the [error message](https://travis-ci.org/liip/LiipFunctionalTestBundle/jobs/116219584#L411) in Travis CI:

> [RuntimeException]
>
> Log file /tmp/PT_vg8xyO is empty. This means a PHPUnit process has crashed.

- [x] Analyze files added in #253, see 4f019b3a327ad7266d7c123b3dbb73a18f3a7e9e
- [x] prepare next release, we should do the same as 1.5: https://github.com/liip/LiipFunctionalTestBundle/commit/8c4cd9f8bc646032f31f44e0c4c88476a8f5b1d9

Separate tasks:
- [x] The last line of the `loadFixtureFiles` method is not tested anymore because the `hautelook_alice.fixtures.loader` service is available with the default configuration

**Comment by alexislefebvre** [comment]
Hi @huitiemesens, you used [`is_file()`](https://github.com/liip/LiipFunctionalTestBundle/blob/4bd881a39b0533fbdf0e6e5e5ae05580c0775dda/Command/RunParatestCommand.php#L71) but my `vendor/bin/paratest` is a link:

    ls -l vendor/bin/paratest 
    lrwxrwxrwx 1 . . 33 .  17 23:31 vendor/bin/paratest -> ../brianium/paratest/bin/paratest*

But [`is_file()`](http://php.net/manual/en/function.is-file.php) expect a regular file. Did it work for you?

**Comment by alexislefebvre** [comment]
Work in progress on https://github.com/alexislefebvre/LiipFunctionalTestBundle/tree/1.6-dev

**Comment by alexislefebvre** [comment]
@huitiemesens It worked for me once I added full paths to `phpunit` and configuration files: https://github.com/alexislefebvre/LiipFunctionalTestBundle/commit/1dfdae467755b3c67b1260517a44840c3441c159

**Comment by alexislefebvre** [comment]
But these changes may break tests LiipFunctionalTestBundle is used in a Symfony app.

Maybe we can run tests with paratests independently, on Travis CI and Scrutinizer we can launch paratest tests after the other tests.

**Comment by huitiemesens** [comment]
@alexislefebvre tell me what you need on this , usually vendor bin are located in ROOT_DIR/bin folder in a symfony but since there is no such a dir in liipfunctionbundle tree, i located it in /vendor/bin to perform tests, which is not the best fix i agree.

**Comment by alexislefebvre** [comment]
- [ ] the test command should not be declared outside of this Bundle's test, or renamed to a more specific name

**Comment by alexislefebvre** [comment]
We can remove most of `Process` calls and use `runCommand()`, as in https://github.com/liip/LiipFunctionalTestBundle/blob/1562ff83f3030b4f8afae9c100ac0253be372e6d/Tests/Test/WebTestCaseConfigPhpcrTest.php#L49 This work without relying on `app/console` so it ease tests. I'll test this later.

**Comment by alexislefebvre** [comment]
- [ ] Test this Bundle with paratest configuration, for example in a new AppKernel.

**Comment by alexislefebvre** [comment]
See #258.
