### ISSUE TITLE
Database doesn't reload if a dependent fixture changes

### ISSUE THREAD

**Issue by cmfcmf** [liip/LiipFunctionalTestBundle#257]
My database didn't update when I changed the contents of a dependent fixture:

Test case:
```php
$this->loadFixtures([AFixture::class]);
```
AFixture:
```php
class AFixture implements DependentFixtureInterface {
// ...
    public function getDependencies()
    {
        return [DependencyFixture::class];
    }
}
```
config_test.yml
```yml
liip_functional_test:
    cache_sqlite_db: true
```
If you now alter the `DependencyFixture` class, the database is not updated when the test case is executed. (using Symfony 3 + latest version of the bundle).

**Comment by alexislefebvre** [comment]
*If you now alter the `DependencyFixture` class*

How do you do this? I'm pretty sure that the cache don't check the data of the fixture.

**Comment by alexislefebvre** [comment]
When I need to modify an existing fixture, I create a class that use `$temp = $this->getReference('MY_BASE_FIXTURE');` then I can update the fixture and persist it. And I load this fixture in my tests. With this method, each fixture has a known state and can be cached.

**Comment by cmfcmf** [comment]
> How do you do this? I'm pretty sure that the cache don't check the data of the fixtures.

> When I need to modify an existing fixture, I create a class that use $temp = $this->getReference('MY_BASE_FIXTURE'); then I can update the fixture and persist it. And I load this fixture in my tests. With this method, each fixture has a known state and can be cached. Hope this helps.

I am unsure whether I understand your comment and question. 
The issue is that the `\Liip\FunctionalTestBundle\Test\WebTestCase::isBackupUpToDate` method is called with the class names passed to the `loadFixtures` method (-> `[AFixture::class]` in my example). 
The `isBackupUpToDate` method doesn't check whether fixtures defined in the `AFixture::getDependencies()` are up to date (-> `[DependencyFixture::class]` in my example) but only checks whether `AFixture::class` is up to date.

**Comment by alexislefebvre** [comment]
What do you mean by *fixtures [...] are up to date*? How do you update the fixtures or its dependencies?

**Comment by cmfcmf** [comment]
> What do you mean by fixtures [...] are up to date? How do you update the fixtures or its dependencies?

I change the code inside the `load` method of my `AFixture` or `DependencyFixture` classes.

**Comment by alexislefebvre** [comment]
Thanks, I understand now.

So we should ensure that `isBackupUpToDate()` check the dependencies and not only the parent class. Feel free to submit a PR if you have a solution, otherwise maybe someone will be able to fix this.

As a workaround, you can clean the cache everytime you update a fixture: `php app/console cache:clear --env=test`.
