### ISSUE TITLE
nelmio/alice v3

### ISSUE THREAD

**Issue by theofidry** [liip/LiipFunctionalTestBundle#268]
I apologize for the spammy issue, but as LiipFunctionalTestBundle is a one of the consumer of [alice](https://github.com/nelmio/alice), I though worth informing you that the next version [v3 is on it's way](https://github.com/nelmio/alice/issues/265). So if you noticed something you would like to change at alice level, now is a good time :)

**Comment by theofidry** [comment]
Quick update: Alice 3.x is now in beta, the persistence layer has been moved to [theofidry/AliceDataFixtures](https://github.com/theofidry/AliceDataFixtures) and [HautelookAliceBundle](https://github.com/hautelook/AliceBundle) 2.x is in beta as well.

I do release the upgrade is far from being easy for maintainers (heck I was the first one suffering for it), but if you can see anything I can help with, don't hesitate to ping me :)

**Comment by Kwadz** [comment]
So for the time being, which libraries version should we use to avoid the problem in issue #297?

**Comment by theofidry** [comment]
See my answer in #297. If you are using LiipBundle, use the one LiipBundle is compatible with, this issue only for @lsmith77 if he wants to upgrade LiipBundle to alice 3.x :)

**Comment by Kwadz** [comment]
Sorry @theofidry my question was not clear enough. I was wondering about BC between LiipFunctionalTestBundle, AliceBundle and Alice.

By default, currently:
`liip/functional-test-bundle 1.7.0` uses `hautelook/alice-bundle ~0.2|~1.2`
`hautelook/alice-bundle` uses `nelmio/alice ^3.0-beta3@beta`

Does every version of AliceBundle can be used with either nelmio/alice 2.x or 3.x?

**Comment by theofidry** [comment]
AliceBundle 1.x uses nelmio/alice 2.x, and AliceBundle 2.x uses nelmio/alice 3.x, so LiipFunctionalTestBundle is using alice 2.x

**Comment by lsmith77** [comment]
BTW if someone is willing to investigate a solution that will make us compatible with both, I would be very happy to merge it.

**Comment by theofidry** [comment]
@lsmith77 whilst I don't think I can spare enough time to work on that specifically, I'll be available for any question regarding any migration hurdle. I believe there's a few features that will need to change though.

Alternatively, maybe this part regarding fixtures, can be moved to AliceBundle? I'm not familiar with the whole feature set you are providing for it but if the common ground is large enough, it may be too much duplication to try to upgrade LiipFunctionalTestBundle for that part.

**Comment by Soullivaneuh** [comment]
@lsmith77 Could we drop alice v2 and use directly the v3?

This is backward compatible according to [semver](http://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api).

**Comment by lsmith77** [comment]
also fine for me

**Comment by Soullivaneuh** [comment]
@lsmith77 What about #321?

**Comment by Soullivaneuh** [comment]
BTW, using only `nelmio/alice` v3 would drop support of php 5.6 for people who want to use it.

It's still acceptable according to semver, but is it for you? Or this may be done on a new major.

**Comment by Soullivaneuh** [comment]
> if increasing minimal version numbers of PHP is a BC break or not is still up for debate.

It was for Sonata. :trollface: This is why I prefer to ask. :wink: 

Still, I think it would be good to make all this stuff on a new major and take profit to do a big cleanup.

For example, I'm not sure hautelook_alice is still necessary for nelmio/alice v3 as we need a persistence layer and this was moved here: https://github.com/theofidry/AliceDataFixtures
But I'm not sure, I asked @theofidry for that.

**Comment by theofidry** [comment]
See [my review](https://github.com/liip/LiipFunctionalTestBundle/pull/321#pullrequestreview-73157472) for that :)

**Comment by Soullivaneuh** [comment]
@theofidry I let @lsmith77 to stop me if I'm wrong, but the hautelook integration is for the faker providers rather than the file auto-discovery,
 [according to the documentation](https://github.com/liip/LiipFunctionalTestBundle#hautelookalicebundle-faker-providers).

How about this? Is it still something managed by hautelook if I well understand this: https://github.com/hautelook/AliceBundle/issues/362#issuecomment-335472543

So in this case, we have just two thing:

- The requirement of `theofidry/alice-data-fixtures` to use `nelmio/alice` with persistence
- The optional addition of `hautelook/alice-bundle` for faker provider. But this one must be compatible with `theofidry/alice-data-fixtures`

Am I right?

BTW, `nelmio/alice` 3.x is now stable, but it's not the case of `theofidry/alice-data-fixtures` neither `hautelook/alice-bundle`. Do you know about any ETA for this? :-)

**Comment by theofidry** [comment]
Faker provider and Processors have been respectively moved down to nelmio/alice and AliceDataFixtures :)

ETA for the stable releases: likely a month or two. Maybe a bit more for Hautelook

**Comment by Soullivaneuh** [comment]
> Faker provider and Processors have been respectively moved down to nelmio/alice and AliceDataFixtures :)

So for the need of the [doc](https://github.com/liip/LiipFunctionalTestBundle#hautelookalicebundle-faker-providers), we should just require `theofidry/alice-data-fixtures` and that's all? Do you confirm?

Do you have a doc link about this move? I'll have to update the doc of this one I think.

cc @lsmith77 could you please also confirm that the hautelook integration is currently only here for the provider?

**Comment by lsmith77** [comment]
not sure about hautelook :-/

**Comment by Soullivaneuh** [comment]
@lsmith77 ok I'll try to keep the integration.

Could you please answer about this?

> Still, I think it would be good to make all this stuff on a new major and take profit to do a big cleanup.

So I will know if I can do such work.

**Comment by Soullivaneuh** [comment]
@lsmith77 The hautelook service looks to be used only here with provided files list: https://github.com/liip/LiipFunctionalTestBundle/blob/051fedf6120d2ec3912c36b6de7b98d72ff7ea76/Test/WebTestCase.php#L585

So I don't think it's use for the file detection at all.

If the faker provider is move to alice, then we don't need the hautelook bundle anymore.

**Comment by alexislefebvre** [comment]
Fixed in #379.
