### ISSUE TITLE
How to append fixtures in liip functional test (symfony 2.8)?

### ISSUE THREAD

**Issue by mappedinn** [liip/LiipFunctionalTestBundle#272]
I would like to append fixtures in my functional test based on  [LiipFunctionalTestBundle][1] in symfony 2.8. Even it is a dev database I working on, I do still need to append the fixtures since I will have:

* regional data (country, region, county)
* vehicule brands and models
* ...

Consequently, having the DB purged after each functional test will not be nice for me.

**NOTICE:** Appending fixtures (without purging) through command line is working with success: `php app/console doctrine:fixtures:load --append`

So, below is my functional test:

    <?php
    
    namespace Minn\APIBundle\Tests\Controller;
    
    use Liip\FunctionalTestBundle\Test\WebTestCase as WebTestCase;
    //use Symfony\Bundle\FrameworkBundle\Test\WebTestCase as WebTestCase;
    use Minn\APIBundle\Tests\Fixtures\Entity\LoadBrandData;
    use Doctrine\Common\DataFixtures\Purger\ORMPurger;
    
    class BrandControllerTest extends WebTestCase {
    
        public function setUp() {
            $this->auth = array(
                'PHP_AUTH_USER' => 'restapi',
                'PHP_AUTH_PW' => 'secretpw',
            );
    
            $this->client = static::createClient(array(), $this->auth);
        }
    
        public function testJsonGetPageAction() {
            $fixtures = array('Minn\APIBundle\Tests\Fixtures\Entity\LoadBrandData');
            $this->loadFixtures($fixtures);
            $brands = LoadBrandData::$brands;
            $brand = array_pop($brands);
    
            $route = $this->getUrl('api_1_brand_get_brand', array('id' => $brand->getId(), '_format' => 'json'));
    
            $this->client->request('GET', $route, array('ACCEPT' => 'application/json'));
            $response = $this->client->getResponse();
            $this->assertJsonResponse($response, 200);
            $content = $response->getContent();
    
            $decoded = json_decode($content, true);
            $this->assertTrue(isset($decoded['id']));
        }
        
        // ..
    }

This test purges the DB. So, I tried the code proposed in [link][2] by doing this change:

    // removed code
    $fixtures = array('Minn\APIBundle\Tests\Fixtures\Entity\LoadBrandData');
    $this->loadFixtures($fixtures);

    // new code
    $this->runCommand('doctrine:fixtures:load --append --no-interaction --fixtures=src/Minn/APIBundle/Tests/Fixtures/Entity/LoadBrandData.php');

But, functional test doest not work.

```
There was 1 error:

1) Minn\APIBundle\Tests\Controller\BrandControllerTest::testJsonGetPageAction
Error: Call to a member function getId() on null

/home/amine/NetBeansProjects/minnapi/src/Minn/APIBundle/Tests/Controller/BrandControllerTest.php:27
```

I tried to used options available in the function *loadFixtures()* by doing this change:

    // removed code:
    $fixtures = array('Minn\APIBundle\Tests\Fixtures\Entity\LoadBrandData');
    $this->loadFixtures($fixtures);

    // new code 
    $fixtures = array('Minn\APIBundle\Tests\Fixtures\Entity\LoadBrandData');
    $this->loadFixtures($fixtures, null,'doctrine', ORMPurger::PURGE_MODE_DELETE);

Verdict: DB is always purged after each run of the functional test.

So, any suggestions??

Thanks,

**NB:** bundles versions described in composer.json

        "doctrine/doctrine-fixtures-bundle": "dev-master",
        "phpunit/phpunit": "5.4.*",
        "liip/functional-test-bundle":"1.6.*",
        "guzzle/guzzle": "v3.9.*"

**NB**: I am already asking this question on [stackoverflow](http://stackoverflow.com/questions/37946411/how-to-append-fixtures-in-liip-functional-test-symfony-2-8)
  [1]: https://github.com/liip/LiipFunctionalTestBundle
  [2]: http://stackoverflow.com/questions/14752930/best-way-to-create-a-test-database-and-load-fixtures-on-symfony-2-webtestcase?rq=1

**Comment by alexislefebvre** [comment]
Maybe the fact that the database is purged is a bug, but I'm not sure to understand your problem. Tests are easier to write when they are independent, and you can load as many fixtures as you want in each test: you can load regional and vehicle data in the same time.

**Comment by mappedinn** [comment]
it could be a bug. Nevertheless, I have to tell you that i JUST have one entity for the moment. It is the entity `Brand`. Consequently, I don't think that I do need ordered fixtures for the moment (but regional data is coming).

For the DependentFixutureInterface, can you develop a little bit its ideas?

To finish, the function `loadFixtureFiles()` is proposing a parameter for append. So, why it is not available in `loadFixture()`?

    public function loadFixtureFiles(array $paths = array(), $append = false, $omName = null, $registryName = 'doctrine')

**Comment by alexislefebvre** [comment]
About your failing test, you can use at least 2 ways in order to access the fixtures:

- use getReferenceRepository https://github.com/liip/LiipFunctionalTestBundle/blob/97cedfc1edd51e142044f2db3759bd96ef7a9d5a/Tests/Test/WebTestCaseTest.php#L294
- use the entity manager https://github.com/liip/LiipFunctionalTestBundle/blob/97cedfc1edd51e142044f2db3759bd96ef7a9d5a/Tests/Test/WebTestCaseTest.php#L309

---

Note that it's recommended to test a static URL, not a generated URL:

**Comment by mappedinn** [comment]
Thank you @alexislefebvre for help.

---
First of all, my test is not failing. It worked perfectly. All I need is loading my fixtures with append set to true to avoid getting the database purged!

Any link regarding appending?

---
For your recommendation regarding the static URL, I will take it into considertation.

**Comment by mappedinn** [comment]
The only solution to avoid having the database purged is to create a testing database. To do that, below are the steps:

# config of a testing database

    # the config has to be done in config_test.yml
    doctrine:
        dbal:
            default_connection: default
            connections:
                default:
                    driver:   pdo_mysql
                    host:     "%database_host%"
                    port:     "%database_port%"
                    dbname:   test
                    user:     "%database_user%"
                    password: "%database_password%"
                    charset:  UTF8

# creation of the database and the tables

    // this command is run only once (just for creating the testing db)
    $ php app/console doctrine:database:create --env=test
    // this command is needed when you have new entities
    $ php app/console doctrine:schema:create --env=test
      
# How to load fixtures in you test?
        $fixtures = array('Minn\APIBundle\Tests\Fixtures\Entity\LoadBrandData');
        $this->loadFixtures($fixtures);
        $brands = LoadBrandData::$brands;

Hope it will help others!
