### ISSUE TITLE
assertValidationErrors issue if using twig {{ render(controller(...)) }}

### ISSUE THREAD

**Issue by fakemau5** [liip/LiipFunctionalTestBundle#273]
All the `assertValidationErrors` statements expecting validation errors fail with an empty actual list of validation errors when the page renders another controller with twig `{{ render(controller() }}` tag, even with a dummy controller with empty view.

Tested with Symfony 2.8 and LiipFunctionalTestBundle 1.6.3

**Comment by alexislefebvre** [comment]
Please test the last version: https://github.com/liip/LiipFunctionalTestBundle/releases/tag/2.0.0-alpha14

It contains #491 and should fix the issue.
