### ISSUE TITLE
Clean Database doesn't work for EntityManagers other than default

### ISSUE THREAD

**Issue by thedamnedrhino** [liip/LiipFunctionalTestBundle#276]
Because of [this line](https://github.com/liip/LiipFunctionalTestBundle/blob/master/Test/WebTestCase.php#L487), the `cleanDatabase` call will always result in the default entity manager being cleaned. The `omName` Argument must be passed in the call to `loadFixtures()`.

**Comment by lsmith77** [comment]
ah .. can you submit a PR to fix this?

**Comment by alexislefebvre** [comment]
Here is the related change: https://github.com/liip/LiipFunctionalTestBundle/commit/ba49b4ff535018687e01594d58e8f555eabdff50#diff-f815866dba659cf4e7aebb6fc769c44cL482
