### ISSUE TITLE
RunParatestCommand not working with Symfony 3

### ISSUE THREAD

**Issue by barthuttinga** [liip/LiipFunctionalTestBundle#279]
The console command RunParatestCommand doesn't work with Symfony 3, due to some changed locations:

- It is asumed that Symfony's console script is located at app/console (which is true in Symfony 2). However, in Symfony 3 the script is located in bin/console.

- The test database is placed in app/cache/test (which is de default cache dir for test env in Symfony 2), but in Symfony 3 this has been relocated to /var/cache/test.

I will submit a pull request addressing these issues (will work in both Symfony 2 and 3).

**Comment by alexislefebvre** [comment]
As an alternative, did you try fastest https://github.com/liuggio/fastest ? I use it (with Symfony 2.8 though) and it works perfectly.

**Comment by barthuttinga** [comment]
Not yet ('cause I didn't know it), I will give it a try. Thanks!

**Comment by alexislefebvre** [comment]
I submitted a documentation about fastest in the #281 PR.

**Comment by barthuttinga** [comment]
@alexislefebvre Thanks for submitting docs!

**Comment by alexislefebvre** [comment]
This has been fixed in #280.
