### ISSUE TITLE
[Discussion ?]Load schema even when not using Sqlite

### ISSUE THREAD

**Issue by magnetik** [liip/LiipFunctionalTestBundle#282]
Hi,

I've been using SQLite for some time, but I've been bitten in the face by the differences between SQLIte and MySQL (that we use in production).

Locally, we use vagrant to have a development environment for php and mysql, so I was thinking : why not using a dedicated database that can be cleared every time we run the test. It should be fairly fast because we allocate big virtual machines.

I configured the bundle for this, but it seems that it does not load the database schema when not using SQLLite (from a quick reading of `WebTestCase::loadFixtures` around line 379).

Is there any reason for this?

Thanks

**Comment by alexislefebvre** [comment]
Did you see the [Non-SQLite](https://github.com/liip/LiipFunctionalTestBundle#non-sqlite) section in the README?

**Comment by magnetik** [comment]
Apparently I did not (I thought I had read it all again today)

This difference is still quite surprising, but thanks for the input 👍

**Comment by lsmith77** [comment]
@magnetik I do not think it will be very feasible to wipe the schema for every test when using something else than a file based RDBMS, except for if you maybe use an in memory solution, which is of course possible .. ie. some RDBMS support in-memory table handers, but probably cleaner to setup would just be mounting a ram disk. if you find a setup that works well for you and it requires changes to this Bundle to make it work nicer, please let us know.

**Comment by magnetik** [comment]
For some reason I thought that using MySQL would be faster but after a few tests I saw that I was deeply wrong indeed. 

Thanks for the support :)
