### ISSUE TITLE
Update description of GitHub project.

### ISSUE THREAD

**Issue by hallabro** [liip/LiipFunctionalTestBundle#284]
The current decription reads:

> Some helper classes for writing functional tests in Symfony2

Seeing as it is also compatible with Symfony 3 (looking at `composer.json`) I would suggest removing the `2` from the description as some people may find it confusing.

**Comment by alexislefebvre** [comment]
Can you please submit a Pull Request?

**Comment by hallabro** [comment]
Not really because it cannot be changed through code.

<img width="804" alt="screen shot 2016-10-26 at 12 44 35" src="https://cloud.githubusercontent.com/assets/2978237/19723113/20f0d318-9b7a-11e6-8ed3-80e4432c35dd.png">

I am thinking of this description in case it helps.

**Comment by alexislefebvre** [comment]
Oops sorry, I see. It has to be done by the maintainer, ping @lsmith77.

**Comment by lsmith77** [comment]
done
