### ISSUE TITLE
Add parameter for paratest bin path

### ISSUE THREAD

**Issue by kamilwalas85** [liip/LiipFunctionalTestBundle#285]
Currently path to paratest is harcoded as 'vendor/bin/paratest' in https://github.com/liip/LiipFunctionalTestBundle/blob/master/Command/RunParatestCommand.php#L73
It would be nice to pass it as parameter exactly the same as liip_functional_test.paratest.phpunit for phpunit path

**Comment by kamilwalas85** [comment]
Also path to phpunit.xml.dist is hardcoded.

**Comment by kick-the-bucket** [comment]
Also the `paratest:run` command just dies after creating schema (at least with Symfony 3.3).

**Comment by alexislefebvre** [comment]
We dropped the support of paratest in #560
