### ISSUE TITLE
PHPUnit 6.0 support

### ISSUE THREAD

**Issue by mvar** [liip/LiipFunctionalTestBundle#307]
Hi. Are there any plans to support PHPUnit 6.0 soon?

**Comment by aserratorta** [comment]
Or, is it would be a valid workaround installing symfony/phpunit-bridge ^2.7|~3.0 ?

**Comment by vpassapera** [comment]
dev-master bridge + https://github.com/TYPO3/class-alias-loader

**Comment by alexislefebvre** [comment]
See #322.
