### ISSUE TITLE
Can't execute phpunit outside the test case class when using yml fixtures

### ISSUE THREAD

**Issue by Kwadz** [liip/LiipFunctionalTestBundle#309]
Currently `phpunit` can be executed from the directory of the test case class only, else we get the following exception while loading fixtures with relative path:

`PHP Fatal error: Uncaught InvalidArgumentException: Unable to find file "../../Resources/fixtures/orm/my_fixture.yml"`

**Comment by alexislefebvre** [comment]
Can't you call `dirname()` (or `__DIR__`) in order to get an absolute path?

```
$this->loadFixtureFiles(array(
     dirname(__FILE__).'/../../Resources/fixtures/orm/my_fixture.yml',
));

**Comment by Kwadz** [comment]
Yes, of course. Why do you prefer to ask the user to manage relative paths while the bundle could do it? Do you find the way with the bundle too complex?

Yes, we could either correct the documentation (to let the user manage that) or implements the feature in the bundle.

**Comment by Kwadz** [comment]
So, do we update the documentation like this:

```
$this->loadFixtureFiles(array(
    __DIR__ . '/../../Resources/fixtures/orm/processor.yml',
));
```

or do we implement the "phpunit from everywhere" support?
