### ISSUE TITLE
Changed signature of `loadFixtures()` (BC break in #310)

### ISSUE THREAD

**Issue by corphi** [liip/LiipFunctionalTestBundle#311]
According to [Symfony BC promise rules](https://symfony.com/doc/current/contributing/code/bc.html#changing-classes), adding a default parameter value to a protected method is not allowed. That is for a reason; we have test traits to do various init tasks; some need to load fixtures and have an abstract method to enforce its (old) signature. PHP now quits with a fatal error.

So, what about a new method instead that purges the database by calling `loadFixtures([])`? (Splitting loading and purging will probably ease [appending fixtures](https://github.com/liip/LiipFunctionalTestBundle/pull/174))

Btw.: The readme still recommends using an empty array to purge the database.

**Comment by alexislefebvre** [comment]
Thanks for your report. Can you please share the message associated to the fatal error?

**Comment by corphi** [comment]
```
Fatal error: Declaration of Random\Fixture\Loading\TestTrait::loadFixtures(array $classNames, $omName = NULL, $registryName = 'doctrine', $purgeMode = NULL) must be compatible with Liip\FunctionalTestBundle\Test\WebTestCase::loadFixtures(array $classNames = Array, $omName = NULL, $registryName = 'doctrine', $purgeMode = NULL)
```
