### ISSUE TITLE
Remove HHVM support?

### ISSUE THREAD

**Issue by ruudk** [liip/LiipFunctionalTestBundle#326]
Tests fail on Travis:
> HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.

See https://travis-ci.org/liip/LiipFunctionalTestBundle/jobs/238420775

**Comment by alexislefebvre** [comment]
Is HHVM supported on Travis CI's Trusty?

**Comment by ruudk** [comment]
Seems like it. Do we want to switch to that?

**Comment by alexislefebvre** [comment]
I would like to wait the merge of the ongoing PR #322 before changing the test suite. Or the test suite should be uploaded in this PR. I don't know yet.

**Comment by Soullivaneuh** [comment]
HHVM support is dropped from Symfony, so it would make sense to drop it here.

**Comment by alexislefebvre** [comment]
We already removed it from tests: https://github.com/liip/LiipFunctionalTestBundle/commit/082a2134a1c2d3fc3a9a75952cca8e4e5ddf80c0#diff-354f30a63fb0907d4ad57269548329e3

So I'm closing it.
