### ISSUE TITLE
Deprecation warning while loading fixtures

### ISSUE THREAD

**Issue by renan-taranto** [liip/LiipFunctionalTestBundle#328]
Hi,
The WebTestCase's `loadFixtures()` method throws a deprecation warning on Symfony 3.3 projects:
``` Using the comma as a group separator for floats is deprecated since version 3.2 and will be removed in 4.0 ```
Related to https://github.com/symfony/symfony/pull/18785/commits/3f3623df271ba9da658cb3578d79f55316c9884b:

**Comment by alexislefebvre** [comment]
Hi,
do you use commas in your fixtures?

**Comment by renan-taranto** [comment]
No @alexislefebvre 
Right now this is the only fixture I have in the project

    class LoadUserData extends AbstractFixture implements OrderedFixtureInterface
    {
        public function load(ObjectManager $manager): void
        {
            $user = $this->createUser('joey');
            $manager->persist($user);
            $manager->flush();
            $this->addReference('user', $user);
        }
    
        private function createUser(
            string $username,
            string $password = '$2y$13$JTAzYtc2aRE0Ma3gYpxmbeI6vuxy1uJcok1Dg/QKgaVwiqrrsngae'     //Password = 12345678
        ): User {
            return new User($username, $password);
        }
    
        public function getOrder(): int
        {
            return 1;
        }
    }

**Comment by renan-taranto** [comment]
I had a comma wrongly placed in my yaml doctrine mappings like this

            password:
                type: string
                length: 64,

Removing it solved the problem. Sorry.

Closing
