### ISSUE TITLE
session.storage.mock_file or session.storage.filesystem?

### ISSUE THREAD

**Issue by Soullivaneuh** [liip/LiipFunctionalTestBundle#336]
At the beginning of the README, we can see the `session.storage.mock_file` usage: https://github.com/liip/LiipFunctionalTestBundle#installation

Later on another exameple, we can see the `session.storage.filesystem` usage: https://github.com/liip/LiipFunctionalTestBundle#logging-in-a-user-using-webtestcaseloginas

Which one to use? Do you have an typo somewhere?

**Comment by alexislefebvre** [comment]
According to [this SO answer](https://stackoverflow.com/a/29563414/2257664), `session.storage.filesystem` is an alias of `session.storage.mock_file`. So both values can be used.

But you're right, the bundle could recommend to use only one of these values.

I think that `session.storage.mock_file` is more explicit than `session.storage.filesystem`. so I suggest replacing `session.storage.filesystem` by `session.storage.mock_file`.
