### ISSUE TITLE
Make classes final?

### ISSUE THREAD

**Issue by soullivaneuh** [liip/LiipFunctionalTestBundle#380]
We should take benefit of the next major release to make most of the classes final.

**Comment by alexislefebvre** [comment]
According to the [official documentation](http://php.net/manual/en/language.oop5.final.php):

> If the class itself is being defined final then it cannot be extended.

So users wouldn't be able to extend the class of this Bundle? Can you please explain the benefits for the users? Thanks.

**Comment by Jean85** [comment]
The benefit it's for us maintainers, not for the end user. @Soullivaneuh's point IMO is that a lot of classes here are for internal usage, not for being extended by the end user.

**Comment by Soullivaneuh** [comment]
@Jean85 Exactly. Plus, on most of the case, user can use composition instead.

See also: https://ocramius.github.io/blog/when-to-declare-classes-final/

**Comment by Jean85** [comment]
I agree on the principle, but I would like to see which classes you would like to make final, so we can see if there's some fringe cases.

**Comment by Soullivaneuh** [comment]
@Jean85 In any case, if making a class final was a mistake, remove the final keyword is BC, not the reverse. :wink: 

This is why I suggest to do it before the 2.0 release.

**Comment by alexislefebvre** [comment]
Some classes were marked as `final` in #436, do we need to do the same thing to other classes?
