### ISSUE TITLE
Include database creation in a method

### ISSUE THREAD

**Issue by alexislefebvre** [liip/LiipFunctionalTestBundle#394]
A part of the documentation explains how to create a database in `setUp()`: https://github.com/liip/LiipFunctionalTestBundle/blob/25aec2050461bc2ab01dcb1e2619d4259ca0eeda/README.md#non-sqlite

This code should be added in a method in order to remove the need to copy and paste it in every project that uses MySQL (and other databases?).

**Comment by Jean85** [comment]
That would make sense, and obviously we would require the fixtures as an array argument...
It could be helpful with #391, because this method could be the one dedicated to the non-append situation, and instead an other one could be dedicated to the append situation.

**Comment by alexislefebvre** [comment]
It looks like database is already created succesfully: https://github.com/liip/LiipFunctionalTestBundle/blob/b919a90c7c933be7085705e1dd0edffecd25a70f/src/Services/DatabaseTools/ORMDatabaseTool.php#L54

**Comment by alexislefebvre** [comment]
I'm closing this since it's done automatically for SQLite and MySQL, see #426 for reference.
