### ISSUE TITLE
Unable to use loginAs for some unknown reason

### ISSUE THREAD

**Issue by gnat42** [liip/LiipFunctionalTestBundle#400]
Hello,

  I use this bundle in a handful of projects and for functional tests use the loginAs and makeClient() calls. I have a project where we just started adding functional tests so we added the bundle and started making calls. When we go to the tests that require a login we did the following:

```
    public function login()
    {
        $em = $this->getContainer()->get('doctrine.orm.entity_manager');
        /** @var User|null $user */
        $user = $em->getRepository(User::class)->findOneBy(['email' => 'schmidt.percival@gmail.com']);
        if ($user === null) {
            throw new \RuntimeException("Unable to find user 'schmidt.percival@gmail.com'");
        }

        $this->loginAs($user, 'default'); // matches the firewall we care about here.
        return $this->makeClient();
    }

    public function testSimpleGet()
    {
        $client = $this->login();
        $client->followRedirects();
        $crawler = $client->request('GET', '/practice/dashboard');
        $this->assertStatusCode(200, $client);
        $this->assertSame(1,$crawler->filterXPath("//h6[@class='widget-title']")->count());
    }
```

This however doesn't result in the proper page, it goes to the login page instead. We checked other projects and they work essentially the same way. We've gone down into the guts and see that there is a session file stored in var/cache/test/sessions/x based on the session id. It creates the token, saves it in the session etc. However the logs shows this.

```
doctrine.DEBUG: SELECT ... FROM nsp_users t0 WHERE t0.email = ? LIMIT 1 ["schmidt.percival@gmail.com"] []
request.INFO: Matched route "practiceDashboard". ... "request_uri":"http://localhost/practice/dashboard","method":"GET"} []
security.INFO: Populated the TokenStorage with an anonymous Token. [] []
security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/local/prolegis/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:68)"} []
security.DEBUG: Calling Authentication entry point. [] []
```

Any ideas why it doesn't see the proper token?

**Comment by alexislefebvre** [comment]
Hello,
did you configure the firewall properly?

**Comment by gnat42** [comment]
Are you asking if the firewall works properly outside of the functional tests. It does so I presume it's configured correctly. It works as expected in the pros and Dev environment as well as test if I add an app_test.pho file and use these test accounts through a browser.

**Comment by gnat42** [comment]
This indeed fixes the issue! I checked the docs and they only talk about setting that parameter here:

> If you get the error message "Missing session.storage.options#name", you have to simply add to your  config_test.yml file the key name:

I never received that message. Should I open a PR against the documentation and update that to just say its required to do that to login?

**Comment by gnat42** [comment]
This is a documentation issue more than a bug. The doc PR is open. Time to close this.
