### ISSUE TITLE
WebTestCase cannot get private session service with symfony 4

### ISSUE THREAD

**Issue by yakobe** [liip/LiipFunctionalTestBundle#404]
After updating to symfony 4 I get the following error:

`Symfony\Component\DependencyInjection\Exception\RuntimeException: The definition for "session" has no class. If you intend to inject this service dynamically at runtime, please mark it as synthetic=true. If this is an abstract definition solely used by child definitions, please add abstract=true, otherwise specify a class to get rid of this error.`

This is because the session service is private and WebTestCase is trying to get it [directly from the container](https://github.com/liip/LiipFunctionalTestBundle/blob/d028d2af57adb049c84927f3a41d79557cc8c279/Test/WebTestCase.php#L776).

**Comment by yakobe** [comment]
Is this a known problem? Packagist says it should be compatible with `symfony/framework-bundle: ^3.4 || ^4.0`. Or am i missing some sort of configuration?

**Comment by alexislefebvre** [comment]
What version if this bundle do you use? You can test the next major release that is still in alpha but is compatible with Symfony 4.0: `composer require --dev "liip/functional-test-bundle:~2.0@dev"`.

**Comment by yakobe** [comment]
I am currently on dev-master. I would prefer not to have to upgrade too many things at the same time if possible. It seems dev master should be compatible with Symfony 4? Any ideas how to get the private service public? There is some docs with Symfony saying to re-declare them in services_test.yaml, but I am not sure if that works for the session service?

**Comment by yakobe** [comment]
Looking at WebTestCase for version 2.0, it also gets the session directly from the container. So it will have the same problem.

**Comment by tomtomau** [comment]
We're using `"liip/functional-test-bundle": "2.0.0-alpha1"` and not having any issues.

It appears as if Session service is public?
```
$ bin/console debug:container session

Information for Service "session"
=================================

 ---------------- -------------------------------------------------- 
  Option           Value                                             
 ---------------- -------------------------------------------------- 
  Service ID       session                                           
  Class            Symfony\Component\HttpFoundation\Session\Session  
  Tags             -                                                 
  Public           yes                                               
  Synthetic        no                                                
  Lazy             no                                                
  Shared           yes                                               
  Abstract         no                                                
  Autowired        no                                                
  Autoconfigured   no                                                
 ---------------- -------------------------------------------------- 

```

**Comment by Jean85** [comment]
@yakobe the error `The definition for "session" has no class.` is not due to private service, it's probably because you didn't activate it and the `session` service do not exist altogether. Did you configure the 'framework.session` option in your Symfony configuration? Did you override that in the test environment?

**Comment by yakobe** [comment]
Thanks for the heads up! It appears someone was overriding the session in the project and making it private. I have done some cleanup and it works perfectly. 
Thank you for the help 👍
