### ISSUE TITLE
Backup is wrong

### ISSUE THREAD

**Issue by eugenekurasov** [liip/LiipFunctionalTestBundle#415]
Hi,
when we load fixtures first time - they are saved to backup files with extension .ser
Here is example code where I am expected to have 3 backup files but got only 2.

```
$this->loadFixtures([SomeFixture1::class, SomeFixture2::class], $append = false);
.....
$this->loadFixtures([SomeFixture3::class], $append = true);
....
// This is fixture will be load from backup with data from SomeFixture1, SomeFixture2
$this->loadFixtures([SomeFixture3::class], $append = false);
```

Can I disable loading fixtures from cache?

**Comment by alexislefebvre** [comment]
Hi,
do you use the version 1 or 2 of this bundle? You mention a problem with number of backup files, but are your fixtures loaded correctly?

**Comment by alexislefebvre** [comment]
> Can I disable loading fixtures from cache?

Yes, this is the default behaviour of the bundle.

Did you set `liip_functional_test.cache_sqlite_db: true` in your configuration?

**Comment by eugenekurasov** [comment]
```liip/functional-test-bundle 2.0.0-alpha4``` 

Fixture loaded not corrected. From my example: ```$this->loadFixtures([SomeFixture3::class], $append = false);``` I expect data only from SomeFixture3

Yes I set ```liip_functional_test.cache_sqlite_db: true```.

**Comment by alexislefebvre** [comment]
My mistake, the new parameter for caching database is this one:

```
liip_functional_test:
        cache_db:
            sqlite: liip_functional_test.services_database_backup.sqlite
```

Source: https://github.com/liip/LiipFunctionalTestBundle/blob/d3f3452aa7c2a82d2316dc0042602a8ba08955ed/UPGRADE-2.0.md

**Comment by eugenekurasov** [comment]
@alexislefebvre thanks.

But if cache is on, backup is wrong. You can [see](https://github.com/liip/LiipFunctionalTestBundle/blob/2.0.0-alpha4/src/Services/DatabaseTools/ORMSqliteDatabaseTool.php#L39) that append option does not use in backup service.

**Comment by eugenekurasov** [comment]
@alexislefebvre thank you for work around.

I rewrited test to avoid this situation, so I hope someone going to fix it.

**Comment by alekseytupichenkov** [comment]
I'll fix it soon

**Comment by alekseytupichenkov** [comment]
I'll fix it in PR #462

**Comment by alexislefebvre** [comment]
I confirm the bug, here is a PR that reproduce the issue: https://github.com/liip/LiipFunctionalTestBundle/pull/476

**Comment by alexislefebvre** [comment]
@eugenekurasov I rewrote the handling of fixtures cache in #476, you can try to use the last release of this bundle and see if issues have been fixed.

**Comment by alexislefebvre** [comment]
I'm closing this issue, feel free to reopen it if the problem is still here.
