### ISSUE TITLE
The max_query_count should not be null

### ISSUE THREAD

**Issue by Soullivaneuh** [liip/LiipFunctionalTestBundle#424]
On the configuration, the `max_query_count` default to `null` if not provided.

This will produce this kind of error if you try to access some services using it:

```
TypeError: Argument 1 passed to Liip\FunctionalTestBundle\QueryCounter::__construct() must be of the type integer, null given, called in /code/var/cache/test/ContainerCnyk14m/getLiipFunctionalTest_Query_CounterService.php on line 8
```

You should provide an integer value as default instead IMO.

**Comment by alexislefebvre** [comment]
Fixed in #453.
