### ISSUE TITLE
assertValidationErrors not working ?.

### ISSUE THREAD

**Issue by nikophil** [liip/LiipFunctionalTestBundle#430]
Hello,

symfony version : 4.1
phpunit version : 7.2
bundle version : 2.0.0-alpha4

i got an odd behavior with the function assertValidationErrors :
I know that i actually have a validation error, the form is quite simple, with 4 fields.

This sample of code fails :
```php
$form->setValues($values);
$client->submit($form);
$this->assertStatusCode(302, $client);
```
```
1) App\Tests\Controller\EasyAdmin\ClosingControllerTest::testNewValidationError
Unexpected validation errors:
+ data.contact: closing.error_contact

Failed asserting that 200 matches expected 302.
```

But, when i call this sample of code :
```php
$form->setValues($values);
$client->submit($form);
$this->assertStatusCode(200, $client);
$this->assertValidationErrors([], $this->getContainer());
```
it passes great the test, although i actually got an error...
and obvously : `$this->assertValidationErrors(['data.contact'], $this->getContainer());` fails...

thanks for your help on this

**Comment by alexislefebvre** [comment]
In the tests we call the `client`'s container:

    $this->assertValidationErrors(['children[name].data'], $this->client->getContainer());

Source: https://github.com/liip/LiipFunctionalTestBundle/blob/afddaec6953fa0d2217c1aa67a49da5259503a1e/tests/Test/WebTestCaseTest.php#L677

---

Can you try to use `$this->assertValidationErrors([], $client->getContainer());` in your test?

**Comment by nikophil** [comment]
okay it's working, sorry for that, thanks for your help & quick answer
