### ISSUE TITLE
WebTestCase::getContainer should return the test container if available

### ISSUE THREAD

**Issue by Soullivaneuh** [liip/LiipFunctionalTestBundle#442]
Ref: https://symfony.com/blog/new-in-symfony-4-1-simpler-service-testing

In a nutshell, in order to access to all the service even if inlined, we must use the special test container.

It can be achieve with ease this way and will keep BC with older versions:

https://github.com/symfony/symfony/blob/ce2ac0f2f0cb0cf6b40ab82ed6267850230197b3/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php#L70

**Comment by alexislefebvre** [comment]
Fixed in #443.
