### ISSUE TITLE
[1.x] Remove invalid tags

### ISSUE THREAD

**Issue by alexislefebvre** [liip/LiipFunctionalTestBundle#458]
**Is your feature request related to a problem? Please describe.**
The `composer.json` file in tags from `1.9.0` to `1.9.4` declare that the bundle is compatible with Symfony 4 but it doesn't work.

See #408

**Describe the solution you'd like**
Jean85 asked about this on Composer's repository: https://github.com/composer/composer/issues/7194#issuecomment-376820987

And we had an [answer from Seldaek](https://github.com/composer/composer/issues/7194#issuecomment-380728223):

> If you published a bad version, just publish a fix version (n+1, avoid reusing the same tag) and move on. In the example above of the LiipFunctionalTestBundle it's a bit problematic because the old version might get picked if you use Symfony 4 at least until you release a version supporting Symfony 4. In that case maybe deleting the tag from the git repo and deleting the tag on packagist is the best course of action. People that have it in their composer.lock will still be able to install as the commit is still there and the lock file has the commit reference, but you stop the bad version from spreading further at least.

So we can delete these tags from the repository and from Packagist, it won't break CIs, that was my fear with this removal, and it won't happen.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by lsmith77** [comment]
done

**Comment by alexislefebvre** [comment]
Great, thanks!

**Comment by dominikzogg** [comment]
#507

**Comment by corphi** [comment]
What about declaring a conflict with affected versions in the Symfony 4 project? You don’t get the bad versions and can drop the local constraint when your minimum requirements surpasses it. Projects I maintain usually collect about a dozen excludes for certain package versions that either contain a bug or don’t work when combined with other packages.
