### ISSUE TITLE
Kernel created by getContainer should by shutdown by KernelTestCase::ensureKernelShutdown

### ISSUE THREAD

**Issue by ruudk** [liip/LiipFunctionalTestBundle#469]
### Preconditions
2.0.0-alpha6

### Steps to reproduce
I'm calling `\Liip\FunctionalTestBundle\Test\WebTestCase::getContainer` and it creates a Kernel. But it doesn't put the kernel in `static::$kernel`. That is needed because it allows  KernelTestCase::ensureKernelShutdown to properly shutdown the kernel.

If you want, I can create a PR to fix it like this:
```diff
     protected function getContainer(): ContainerInterface
     {
         $cacheKey = $this->environment;
         if (empty($this->containers[$cacheKey])) {
             $options = [
                 'environment' => $this->environment,
             ];
-             $kernel = $this->createKernel($options);
+             static::$kernel = $this->createKernel($options);
-             $kernel->boot();
+             static::$kernel->boot();
 
-             $this->containers[$cacheKey] = $kernel->getContainer();
+             $this->containers[$cacheKey] = static::$kernel->getContainer();
         }
 
         return $this->containers[$cacheKey];
     }
```

**Comment by ruudk** [comment]
I'm not really sure why `getContainer` has support for starting and keeping track of containers in different environments. Makes it more complicated, maybe good to drop this in 2.0? :)

**Comment by Jean85** [comment]
It's done to cache it. It's the main reason why I'm using this bundle now, but I should test if disabling the cache has real perfomance impact at this point.

**Comment by ruudk** [comment]
But who would want to have containers in different environments? I feel like that is an edge case, and most people just use 1 environment for testing.
