### ISSUE TITLE
phpdbg crash using WebTestCase

### ISSUE THREAD

**Issue by Jerome1337** [liip/LiipFunctionalTestBundle#479]
### Preconditions
1. Bundle version 2.0-alpha10
2. PHP v7.2.13
3. phpdbg v0.5.0
4. phpunit v7.5.1

You can use https://hub.docker.com/r/jerome1337/php-dev to have exactly the same env I use.

### Steps to reproduce

1. Create a phpunit functional test

```
<?php

declare(strict_types=1);

namespace App\Tests;

use Tests\AppBundle\Controller\WebTestCase;

final class BarTest extends WebTestCase
{
    public function test() {
        $this->assertTrue(true);
    }
}
```

2. Create an abstract WebTestCase

```
abstract class WebTestCase extends BaseTestCase
{
    /**
     * @var mixed[]
     */
    private $fixtures;

    /**
     * {@inheritdoc}
     */
    protected function setUp(): void
    {
        parent::setUp();

        $this->fixtures = $this->loadFixtureFiles(\array_merge([
            ...
        ], []));
    }
}
```

3. Launch the test using

```
phpdbg -qrr vendor/bin/phpunit tests/BarTest.php --debug --coverage-php coverage/coverage.php --colors=never
```

### Expected result
1. This test should be finished and return 

```
PHPUnit 7.5.1 by Sebastian Bergmann and contributors.

Test 'App\Tests\BarTest::test' started
Test 'App\Tests\BarTest::test' ended


Time: 527 ms, Memory: 8.00MB

OK (1 test, 1 assertion)

Generating code coverage report in PHP format ... done
```

### Actual result
1. Instead I have the test starting and never finishing

```
PHPUnit 7.5.1 by Sebastian Bergmann and contributors.

Test 'App\Tests\BarTest::test' started
```

I search inside `WebTestCase` class and I found that the test stop to continue when 

```
$kernel->boot();
```

is called inside the `getContainer` method.

**Comment by Jerome1337** [comment]
This issue is probably from Symfony kernel. I opened an issue on Symfony repo (https://github.com/symfony/symfony/issues/29656)

**Comment by alexislefebvre** [comment]
Thanks. We could reopen this issue if the error comes from this bundle.
