### ISSUE TITLE
Tag 1.9.3 was removed

### ISSUE THREAD

**Issue by dominikzogg** [liip/LiipFunctionalTestBundle#507]
Until yesterday the bundle was installable by the tag 1.9.3 side by side with phpunit 7.5 and worked for our project, now the tag is gone and we're in a situation we cannot recover, cause no newer version is stable and supports phpunit 7.5.

**Comment by corphi** [comment]
The commit 80329104370eabebc10df69c15e98f585773884d was tagged 1.9.3.

**Comment by lsmith77** [comment]
what is the issue with 1.9.5?

**Comment by dominikzogg** [comment]
Conflict with phpunit >= 7

Lukas Kahwe Smith <notifications@github.com> schrieb am Fr., 10. Mai 2019,
11:46:

**Comment by lsmith77** [comment]
@alexislefebvre I guess we could try to get a 1.94.1 one released that disallows Symfony 4 but works for phpunit 7 and Symfony 3. wdyt?

**Comment by alexislefebvre** [comment]
Sorry for the inconvenience.

Does https://packagist.org/packages/liip/functional-test-bundle#1.10.0 fit your needs?

**Comment by dominikzogg** [comment]
@alexislefebvre we're using phpunit 7.5, so no

**Comment by alexislefebvre** [comment]
Sorry, I missed that it was noted in `Conflicts`. :see_no_evil:

**Comment by alexislefebvre** [comment]
I upgraded dependencies in #508, it could be released as `1.11.0` (because requiring PHP 7.1 is a great change, and [1.10.0](https://github.com/liip/LiipFunctionalTestBundle/releases/tag/1.10.0) is the last release from master, not 1.9 :wink:).

**Comment by corphi** [comment]
It would work for me; I am running PHP 7.2 and PHPUnit 7.5, but can’t upgrade to Symfony 3.4 quite yet. I’ll fire up a test run tomorrow. Thanks.

**Comment by alexislefebvre** [comment]
Please try the 1.11. version: https://github.com/liip/LiipFunctionalTestBundle/releases/tag/1.11.0

**Comment by alexislefebvre** [comment]
Please try the 1.11.0 version: https://github.com/liip/LiipFunctionalTestBundle/releases/tag/1.11.0
