### ISSUE TITLE
Compatibility with Symfony 4.3.0-BETA1

### ISSUE THREAD

**Issue by gnutix** [liip/LiipFunctionalTestBundle#509]
Running any test extending `Liip\FunctionalTestBundle\Test\WebTestCase` result in : 

```
TypeError: Return value of Liip\FunctionalTestBundle\Test\WebTestCase::makeClient()
must be an instance of Symfony\Bundle\FrameworkBundle\Client, instance of
Symfony\Bundle\FrameworkBundle\KernelBrowser returned

/srv/app/vendor/liip/functional-test-bundle/src/Test/WebTestCase.php:413
```

### Preconditions
* Symfony 4.3.0-BETA1
* LiipFunctionalTestBundle 2.0.0-alpha15 and 3.0.0-alpha1

**Comment by gnutix** [comment]
I've fixed the code with this patch : https://diffy.org/diff/ydi0ltz330f1n73szx1xajor

But I'm not sure if I can do a PR, as it's a BC break for this library I guess.

**Comment by alexislefebvre** [comment]
Thanks, could you please open a PR targeting the `3.x` branch? We'll see if it breaks tests.

**Comment by gnutix** [comment]
There you go : https://github.com/liip/LiipFunctionalTestBundle/pull/510

**Comment by alexislefebvre** [comment]
Thanks for the PR, it fixed the issue for Symfony 4.3 but break tests with all other versions.

I'm still wondering if this is an issue from Symfony that require a change to avoid BC break, see these related issues: https://github.com/symfony/symfony/pull/30541 https://github.com/symfony/symfony/issues/31039 https://github.com/symfony/symfony/pull/31040

**Comment by alexislefebvre** [comment]
We could use an alias as shown in this comment: https://github.com/symfony/symfony/pull/30541#issuecomment-481215018

**Comment by gnutix** [comment]
Not sure how. I get `PHP Fatal error:  Uncaught Cannot declare class Symfony\Component\BrowserKit\Client, because the name is already in use` if I put `class_alias(\Symfony\Component\BrowserKit\AbstractBrowser::class, 'Symfony\Component\BrowserKit\Client');` on top of my `WebTestCase` class (that extends this bundle's one and override `makeClient`).

**Comment by gnutix** [comment]
PR ready.

**Comment by alexislefebvre** [comment]
Thanks a lot! I'll publish a new release.
