### ISSUE TITLE
Support for PHPUnit 8

### ISSUE THREAD

**Issue by MassiveHiggsField** [liip/LiipFunctionalTestBundle#511]
Do you have any plans to support PHPUnit 8? What is missing so far? Can i help?

**Comment by alexislefebvre** [comment]
To my knowledge, there hasn't been work on PHPUnit 8 yet.

Feel free to open a PR with support of PHPUnit 8, it has to be based on the 3.x branch (unreleased yet).

**Comment by alexislefebvre** [comment]
To my knowledge, there hasn't been work on PHPUnit 8 yet.

Feel free to open a PR with support of PHPUnit 8, note that it has to be based on the 3.x branch of this bundle (unreleased yet).

**Comment by MassiveHiggsField** [comment]
Okay, i am gonna try to do that. Do you wanna support both PHPUnit 7 and PHPUnit 8 in the 3.x branch or just v8?

**Comment by alexislefebvre** [comment]
We have to do our best to support PHPUnit 7 since it's supported until February 7, 2020 : https://phpunit.de/supported-versions.html

**Comment by MassiveHiggsField** [comment]
Yep makes sense, i will give it a shot on the coming weekend.

**Comment by alexislefebvre** [comment]
This bundle doesn't require a specific version of PHPUnit, so it's possible to use PHPUnit 8 as shown in #351 

The issue with PHPUnit 8 will be fixed in #541.

**Comment by alexislefebvre** [comment]
Please try the last release: https://github.com/liip/LiipFunctionalTestBundle/releases/tag/3.3.0
