### ISSUE TITLE
[3.x] Ease upgrade from 1.x to 3.x

### ISSUE THREAD

**Issue by alexislefebvre** [liip/LiipFunctionalTestBundle#516]
**Is your feature request related to a problem? Please describe.**
Upgrade from 1.x to 3.x cause several issues if one doesn't read documentation carefully (like most of us do):

- Old configuration `liip_functional_test.cache_sqlite_db: true` causes errors, when Composer run Symfony scripts:

```
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

In ArrayNode.php line 307:

Unrecognized option "cache_db" under "liip_functional_test" 
```
 
- Calls to `loadFixtures` and `loadFixtureFiles` throw fatal errors when running tests:

```
Error: Call to undefined method […]Test::loadFixtures()
```

**Describe the solution you'd like**
Errors should show how to ease upgrading

**Describe alternatives you've considered**

- [ ] Add a compatibility layer for old configuration, and/or throw warnings instead of a fatal error, with a link to the documentation that explain upgrade steps
- [ ] Calls to `loadFixtures` and `loadFixtureFiles` should print a text like `This feature has been moved to https://github.com/liip/LiipTestFixturesBundle, please install it` (but only if it doesn't create conflicts when both bundle are active)

**Additional context**

It would be nice if we could deprecate features before removing them, but only if its doesn't require too much work.

**Comment by Simperfit** [comment]
@alexislefebvre I need to do some more tests, but it seems that passing from 2.x to 3.x is making my test x2 longer.

**Comment by alexislefebvre** [comment]
This may be due to an issue with accesses to the container, as reported in #446.

**Comment by alexislefebvre** [comment]
Or, the use of `static::$client`, we can rename `$client` to `$testClient` projects' code in order to avoid the conflict: https://github.com/liip/LiipFunctionalTestBundle/pull/512
