### ISSUE TITLE
[2.x] Cannot install 2.x branch anymore

### ISSUE THREAD

**Issue by PapyDanone** [liip/LiipFunctionalTestBundle#533]
Could be related to #528 

when requiring

    "liip/functional-test-bundle": "2.x-dev"

or 

    "liip/functional-test-bundle": "~2.0@dev"

the installed version ends up being the latest from `master`:

    $ composer show | grep liip

    liip/functional-test-bundle         dev-master ac2c320

Symfony version: `4.3.2`

Am I missing anything? Thanks for the help.

**Comment by jayesbe** [comment]
Same issue. Try "liip/functional-test-bundle": "2.x-dev#464c7a2"

**Comment by alexislefebvre** [comment]
Please try this: `composer require "liip/functional-test-bundle:~2.0@alpha"`

If it doesn't work, please run `composer why-not "liip/functional-test-bundle:~2.0@alpha"` and share the output.

**Comment by alexislefebvre** [comment]
Did you found a solution? Did you try the stable 3.0 release?

**Comment by PapyDanone** [comment]
@alexislefebvre we did end up upgrading to the 3.0 release. 

I also tested `composer require --dev "liip/functional-test-bundle:~2.0@alpha"` and it now resolves to the expected commit hash.

Thanks for the help.
