### ISSUE TITLE
[3.x] WebTestCase and FixturesTrait override (?)

### ISSUE THREAD

**Issue by magnetik** [liip/LiipFunctionalTestBundle#535]
After upgrading from 2.x, I'm confused by the fact that `WebTestCase` and `FixturesTrait` are sharing a lot of code, and defining a lot of properties and method.

It looks like both bundle are really really coupled and I'm quite sure that this will lead to breaking sooner or later.

**Comment by alexislefebvre** [comment]
I agree.

Some properties are not used and can be removed from `FixturesTrait`:https://github.com/liip/LiipTestFixturesBundle/blob/9bd069ffb892d47f2a00861de69a699bd49b7dbe/src/Test/FixturesTrait.php#L29

My biggest concern is `getContainer()`, we may deprecate it and recommend to inject dependencies instead: https://github.com/liip/LiipTestFixturesBundle/issues/18

**Comment by tarjei** [comment]
Should this issue be closed?

**Comment by alexislefebvre** [comment]
LiipFunctionalTestBundle and LiipTestFixturesBundle still define a `getContainer()` method. We don't have a solution yet.

**Comment by alexislefebvre** [comment]
It has been fixed in https://github.com/liip/LiipTestFixturesBundle/pull/26

LiipTestFixturesBundle 2.x doesn't use a trait so there will be less conflicts.
