### ISSUE TITLE
WebTestCase and FixturesTrait define the same property ($containers)

### ISSUE THREAD

**Issue by dnl-jst** [liip/LiipFunctionalTestBundle#548]
```Fatal error: Liip\FunctionalTestBundle\Test\WebTestCase and Liip\TestFixturesBundle\Test\FixturesTrait define the same property ($containers) in the composition of App\Tests\TestCase\FunctionalTestCase. However, the definition differs and is considered incompatible. Class was composed in /var/www/tests/TestCase/FunctionalTestCase.php on line 1```

### Preconditions
PHP 7.2

1. liip/functional-test-bundle 3.3.0
2. liip/test-fixtures-bundle 1.4.0

### Steps to reproduce

``` 
<?php declare(strict_types=1);

namespace App\Tests\TestCase;

use Liip\FunctionalTestBundle\Test\WebTestCase;
use Liip\TestFixturesBundle\Test\FixturesTrait;

class FunctionalTestCase extends WebTestCase
{
    use FixturesTrait;

    [...]
}
```

### Expected result

1. WebTestCase should be useable together with FixturesTrait

### Actual result

![Screenshot from 2019-11-13 22-47-46](https://user-images.githubusercontent.com/712897/68807173-a6ea6a00-0667-11ea-93e9-f00eff58124d.png)

**Comment by alexislefebvre** [comment]
Thanks for the report, it probably comes from https://github.com/liip/LiipTestFixturesBundle/pull/44

**Comment by alexislefebvre** [comment]
Please try last release of the Fixtures bundle: https://github.com/liip/LiipTestFixturesBundle/releases/tag/1.4.1
