### ISSUE TITLE
Allow purging sqlite db with out dropping the existing db

### ISSUE THREAD

**Issue by phillipsb22** [liip/LiipFunctionalTestBundle#566]
**Problem**
I am using a custom build sqlite database that causes issues when I drop and try rebuild here liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMSqliteDatabaseTool.php:63

**Suggested solution**
I would like to implement an additional parameter that gets passed through to the load fixtures function that will allow the database to not be dropped but rather purged liip/test-fixtures-bundle/src/Services/DatabaseTools/ORMSqliteDatabaseTool.php:72

**Additional info**
I would like to know if this is a feature you would like added or do you see problems with adding a feature like this?
I don't see this as a breaking change to existing code, let me know if you would be happy with me implementing this and sending a PR. If so can you please state what you would need to merge it in

**Comment by alexislefebvre** [comment]
Hello, all contributions are welcome!

Please note that test-fixtures-bundle has a different repository: https://github.com/liip/LiipTestFixturesBundle/issues

**Comment by phillipsb22** [comment]
Sorry I did not notice the repo I was in it was supposed to be in the Fixtures Bundle.
I will make the changes
