### ISSUE TITLE
Regression in getContainer with symfony 5.3

### ISSUE THREAD

**Issue by biozshock** [liip/LiipFunctionalTestBundle#592]
After the fix #584 there is no possibility to test `runCommand` with `$reuseKernel = true` when using symfony 5.3+.

### Preconditions
1. Use symfony 5.4 
2. Use `runCommand` test.

When there is a `$this->getContainer()` call before the `runCommand` it's not possible to reuse same kernel.
In the following code there is no possibility to reuse kernel created by `getContainer`.

```php
$client = $this->createMock(Client::class);

$this->getContainer()->get(Service::class)->setClient($client);
$this->runCommand('command', [], true);
```

**Comment by alexislefebvre** [comment]
It looks like it's the same issue as in https://github.com/symfony/symfony/issues/44253
