### ISSUE TITLE
[RFC] Drop support of PHP 7.2 and 7.3?

### ISSUE THREAD

**Issue by alexislefebvre** [liip/LiipFunctionalTestBundle#625]
**Is your feature request related to a problem? Please describe.**

- PHP 7.2 is used by 2.0% of the installations
- PHP 7.3 is used by 2.0% of the installations

See https://packagist.org/packages/liip/functional-test-bundle/php-stats#4

**Describe the solution you'd like**
Drop support of PHP 7.2 and 7.3

**Describe alternatives you've considered**
.

**Additional context**
The support of PHP 7.2 and 7.3 ended in 2020 and 2021 respectively: https://www.php.net/supported-versions.php

**Comment by Chris53897** [comment]
I am in favor of drop support for php 7.4 as well.
I have created a PR https://github.com/liip/LiipFunctionalTestBundle/pull/628
