### ISSUE TITLE
Symfony 7 compatibility

### ISSUE THREAD

**Issue by kl3sk** [liip/LiipFunctionalTestBundle#630]
**Is your feature request related to a problem? Please describe.**
No upgrade to SF 7 possible

**Describe the solution you'd like**
Upgrade to SF 7

**Describe alternatives you've considered**
Downgrade to SF 6.4

Thanks

**Comment by alexislefebvre** [comment]
Thanks for the report.

We can take inspiration from:

- https://github.com/liip/LiipTestFixturesBundle/pull/248

**Comment by alexislefebvre** [comment]
Free free to open a Pull Request with the required changes.

**Comment by kl3sk** [comment]
Ok why not, I'll have a look.

**Comment by alexislefebvre** [comment]
Could you please tell us what methods of this bundle are used in your projects? Some methods have been integrated in Symfony.

**Comment by kl3sk** [comment]
Crap ! You nailed it, none seems to be used any more.

I'll remove the bundle from my project and try some tests that pass 🙄

**Comment by kl3sk** [comment]
Because I was writing functional tests I though this bundle was used,

But it is `LiipTestFixturesBundle` that is used. And seems already ready for Sf7.

My bad.

**Comment by Nirator78** [comment]
Hi,
I'm currently using `LiipFunctionalTestBundle` in my Symfony `6.4` and i can't update in Symfony `7.0` because `LiipFunctionalTestBundle` is not compatible.

> Your requirements could not be resolved to an installable set of packages.
 >  Problem 1
 >    - Root composer.json requires liip/functional-test-bundle 4.10.0 -> satisfiable by liip/functional-test-bundle[4.10.0].
>     - liip/functional-test-bundle 4.10.0 requires symfony/browser-kit ^4.4 || ^5.1 || ^6.0 -> found symfony/browser-kit[v4.4.0, ..., v4.4.44, v5.1.0, ..., v5.4.31, v6.0.0, ..., v6.4.0] but it conflicts with your root composer.json require (7.0.*).

**Comment by alexislefebvre** [comment]
@Nirator78 Could you please tell us what methods of this bundle are used in your projects? Some methods have been integrated in Symfony.

See also:

- GH-633

**Comment by alexislefebvre** [comment]
Please try the last release: https://github.com/liip/LiipFunctionalTestBundle/releases/tag/4.11.0

**Comment by Nirator78** [comment]
I'm actually using the makeClient method and the assertStatusCode method.

**Comment by alexislefebvre** [comment]
> I'm actually using the makeClient method and the assertStatusCode method.

The documentation has been updated to show that built-in functions from Symfony can be used: https://github.com/liip/LiipFunctionalTestBundle/blob/f8e0bd27591ef804cf2c33ee144fedac2e1b1194/doc/basic.md

**Comment by Nirator78** [comment]
Thank i will try this.
