### ISSUE TITLE
Modify loaded datafixtures

### ISSUE THREAD

**Issue by tobiassjosten** [liip/LiipFunctionalTestBundle#68]
My functional tests extends this bundle's `WebTestCase` and using the `setUp()` method I'm loading in the needed fixtures before all tests. The test environment is using SQLite, so to take advantage of the backup file option. This works great … in most cases. :)

However when I have a test that modifies the database somehow, those modifications doesn't seem to take effect when making client requests. For example I first GET / to see that it looks alright with the fixtures and then I make some changes like adding a blog post, before making another request to make sure it still renders as expected. But the blog post is nowhere to be found.

If I double check the database after making the request, the change is definitely still in there. I just can't make sense of that. It's like the request handling's using its own, separate database.

Does anyone know what could be wrong? Or how I could dig in to find the problem myself? Or maybe how I could approach this differently? Any help is greatly appreciated.

**Comment by devantoine** [comment]
I had the same issue. The fix is to merge the loaded fixtures back into the EM.
