### ISSUE TITLE
Stop using deprecated parameter session.storage.options

### ISSUE THREAD

**Issue by fiddike** [liip/LiipFunctionalTestBundle#80]
session.storage.options is currently referenced in makeClient () in
liip\functional-test-bundle\Liip\FunctionalTestBundle\Test\WebTestCase.php

This parameter is deprecated in Symfony 2.1, see http://symfony.com/doc/current/cookbook/configuration/pdo_session_storage.html
"New in version 2.1: In Symfony2.1 the class and namespace are slightly modified. You can now find the session storage classes in the Session\Storage namespace: Symfony\Component\HttpFoundation\Session\Storage. Also note that in Symfony2.1 you should configure handler_id not storage_id like in Symfony2.0. Below, you'll notice that %session.storage.options% is not used anymore."

**Comment by alexislefebvre** [comment]
This code still works with all current Symfony version (even 3.0). Is there really an issue? It looks like there's no problem.

**Comment by alexislefebvre** [comment]
This parameter still exist in Symfony 4: https://github.com/symfony/symfony/search?utf8=%E2%9C%93&q=%22session.storage.options%22&type=

I'm closing this since I don't see any issue.
