### ISSUE TITLE
Documentation of WebTestCase#makeClient and WebTestCase#loginAs

### ISSUE THREAD

**Issue by RLovelett** [liip/LiipFunctionalTestBundle#88]
Using Symfony 2.2 I am trying to make use of the WebTestCase#loginAs method.

```php
$lovelettr = $em->getRepository('MyBundle:User')
    ->findByUsername('lovelettr')[0];

$this->loginAs($lovelettr, 'client');
$client = $this->makeClient();
```
This raises an `InvalidArgumentException` with the message `Missing session.storage.options#name`. What do I need to configure to enable this? I am not seeing it in the documentation.

**Comment by Aerendir** [comment]
@lsmith77 , I think this should be closed, too.

**Comment by lsmith77** [comment]
yes thx
